import { vi } from 'vitest';

window.scrollTo = vi.fn();
URL.createObjectURL = vi.fn(() => 'blob:psyche-test');
HTMLElement.prototype.requestFullscreen = vi.fn();
globalThis.confirm = vi.fn(()=>true);
globalThis.prompt = vi.fn(()=>'Correção solicitada');
document.body.innerHTML = '<div id="app"></div>';
sessionStorage.setItem('psyche:apiToken','test-token');
globalThis.__apiState = {
  user:{id:'usr_1',clinic_id:'cln_1',unit_id:'unt_1',name:'Carolina Martins',email:'admin@psyche.local',role:'admin'},
  patients:[{id:'pat_1',name:'Mariana Costa',email:'mariana@example.com',phone:'11999999999',birth_date:'1990-05-10',status:'active',professional_id:'usr_1',created_at:'2026-08-01T10:00:00Z'}],scheduleRules:{units:{},professionals:{}},
  appointments:[{id:'apt_1',patient_id:'pat_1',professional_id:'usr_1',starts_at:'2026-08-06T11:00:00.000Z',modality:'Online',status:'confirmed',booking_type:'regular',confirmation_status:'confirmed',patient_name:'Mariana Costa',professional_name:'Carolina Martins'}],
  finance:[],team:[{id:'usr_1',name:'Carolina Martins',email:'admin@psyche.local',role:'admin',unit_id:'unt_1',active:1,unit_name:'Jardins',created_at:'2026-01-01T10:00:00Z'},{id:'usr_2',name:'Gustavo Lima',email:'gustavo@psyche.local',role:'professional',unit_id:'unt_1',active:1,unit_name:'Jardins',created_at:'2026-02-01T10:00:00Z'}],
  units:[{id:'unt_1',name:'Jardins',address:'Rua Oscar Freire',rooms:3,active:1}],services:[],inventory:[],inventoryMovements:[],rooms:[],equipment:[],maintenance:[],suppliers:[],payables:[],receipts:[],invoices:[],clinicalRecords:[],psychologicalDocuments:[],settings:{integrations:{patient_portal:true,automatic_confirmation:false,video_consultation:false,payments:false},notifications:{email_appointments:true,email_finance:true,browser_messages:true,daily_summary:false},security:{session_timeout_minutes:480,two_factor_required:false,clinical_audit:true,data_export_enabled:true},clinic:{timezone:'America/Sao_Paulo',locale:'pt-BR'},billing:{timing:'after_session',grace_days:3,overdue_action:'warn',allow_clinical_override:true,cancellation_hours:24,no_show_charge_percent:100,emergency_never_block:true}},campaigns:[],feedback:[],conversations:[{id:'cnv_1',patient_id:'pat_1',patient_name:'Mariana Costa',created_at:'2026-08-05T10:00:00Z'}],messages:[]
};
globalThis.fetch = vi.fn(async (url,options={})=>{
  const path=new URL(url,'http://localhost').pathname.replace('/api',''),method=options.method||'GET',state=globalThis.__apiState;
  const answer=(data,status=200)=>new Response(status===204?null:JSON.stringify(data),{status,headers:{'content-type':'application/json'}});
  if(path==='/health')return answer({status:'ok'});
  if(path==='/auth/login'&&method==='POST'){const input=JSON.parse(options.body);return input.password==='Psyche@2026!'?answer({token:'authenticated-token',user:state.user}):answer({error:'Credenciais inválidas'},401);}
  if(path==='/auth/logout'&&method==='POST')return answer(null,204);
  if(path==='/me')return answer({user:state.user});
  if(path==='/platform/context')return answer({data:{tenant:{id:'cln_1',name:'Psyché Saúde',created_at:'2026-01-01T00:00:00Z'},subscription:{plan_key:'clinic',plan_name:'Clínica',status:'active'},modules:Object.fromEntries(['core','clinical','finance','inventory','communication','marketing','analytics','telehealth'].map(key=>[key,{name:key,enabled:true}])),limits:{users:50,units:10,patients:15000,storage_mb:51200},usage:{users:state.team.length,units:state.units.length,patients:state.patients.length}}});
  if(path==='/platform/modules'&&method==='PATCH'){const input=JSON.parse(options.body);return answer({data:{module_key:input.module_key,enabled:input.enabled}});}
  if(path==='/roles')return answer({data:[{key:'admin',label:'Administrador',permissions:['*']},{key:'professional',label:'Profissional clínico',permissions:['patients:read','patients:write','appointments:read','appointments:write','sessions:read','sessions:write','messages:read','messages:write']},{key:'reception',label:'Recepção',permissions:['patients:read','patients:write','appointments:read','appointments:write','messages:read','messages:write']},{key:'finance',label:'Financeiro',permissions:['patients:read','finance:read','finance:write']}]});
  if(/^\/schedule-rules\/(units|professionals)\/[^/]+$/.test(path)){const[,scope,id]=path.match(/^\/schedule-rules\/(units|professionals)\/(.+)$/);if(method==='GET')return answer({data:state.scheduleRules[scope][id]||[]});const input=JSON.parse(options.body);state.scheduleRules[scope][id]=input.rules;return answer({data:{scope,id,rules:input.rules.length}});}
  if(/^\/appointments\/[^/]+\/confirmation$/.test(path)&&method==='POST'){const item=state.appointments.find(x=>x.id===path.split('/')[2]);item.confirmation_status='pending';state.messages.push({id:`msg_${state.messages.length+1}`,sender_type:'staff',body:'Confirme seu atendimento pelo portal.',created_at:new Date().toISOString()});return answer({data:{appointment_id:item.id,status:'pending'}},201);}
  if(path.startsWith('/dashboard'))return answer({data:{date:'2026-08-06',metrics:{consultations:1,active_patients:state.patients.length,new_patients:1,revenue_cents:30000,revenue_trend:12.5,occupancy:4,capacity:24},agenda:state.appointments,statuses:{confirmed:1},finance:[{month:'2026-03',income:0,expense:0},{month:'2026-04',income:0,expense:0},{month:'2026-05',income:0,expense:0},{month:'2026-06',income:0,expense:0},{month:'2026-07',income:0,expense:0},{month:'2026-08',income:30000,expense:5000}],messages:[],feedback:{average:0,count:0,distribution:{}},updated_at:'2026-08-06T10:00:00Z'}});
  if(path==='/reports/summary'&&method==='GET')return answer({data:{period:{from:'2026-08-01',to:'2026-08-05',days:5},metrics:{appointments:4,completed:3,cancelled:1,completion_rate:75,occupancy_rate:20,new_patients:1,active_patients:state.patients.length,retention_rate:50,income_cents:80000,expense_cents:20000,net_cents:60000,average_ticket_cents:26667},statuses:{completed:3,cancelled:1},professionals:[{id:'usr_1',name:'Carolina Martins',appointments:4,completed:3,losses:1}],daily_appointments:[{date:'2026-08-05',total:4,completed:3}],daily_finance:[{date:'2026-08-05',income:80000,expense:20000}],generated_at:'2026-08-05T18:00:00Z'}});
  if(path==='/finance/summary'&&method==='GET'){const active=state.finance.filter(x=>x.status!=='void'),sum=(type,statuses)=>active.filter(x=>x.type===type&&statuses.includes(x.status)).reduce((total,x)=>total+x.amount_cents,0),received=sum('income',['paid']),expenses=sum('expense',['paid','pending','overdue']);return answer({data:{month:'2026-08',received_cents:received,receivable_cents:sum('income',['pending','overdue']),expenses_cents:expenses,overdue_cents:sum('income',['overdue']),balance_cents:received-expenses,entries:active.length}});}
  if(path==='/conversations/summary'&&method==='GET')return answer({data:{conversations:state.conversations.length,unread:state.messages.filter(x=>x.sender_type==='patient'&&!x.read_at).length,messages_today:state.messages.length}});
  if(path==='/feedback/summary'&&method==='GET'){const count=state.feedback.length,average=count?state.feedback.reduce((sum,x)=>sum+x.score,0)/count:0,positive=state.feedback.filter(x=>x.score>=4).length;return answer({data:{count,average:Number(average.toFixed(1)),positive_rate:count?Math.round(positive/count*100):0,nps:count?Math.round((state.feedback.filter(x=>x.score===5).length-state.feedback.filter(x=>x.score<=3).length)/count*100):0,active_campaigns:state.campaigns.filter(x=>x.status==='active').length,distribution:Object.fromEntries([1,2,3,4,5].map(score=>[score,state.feedback.filter(x=>x.score===score).length]))}});}
  if(path==='/feedback'&&method==='GET')return answer({data:state.feedback});
  if(path==='/feedback'&&method==='POST'){const input=JSON.parse(options.body),item={id:`fdb_${state.feedback.length+1}`,...input,patient_name:state.patients.find(x=>x.id===input.patient_id)?.name,created_at:new Date().toISOString()};state.feedback.push(item);return answer({data:item},201);}
  if(path==='/settings'&&method==='GET')return answer({data:state.settings});
  if(path==='/settings'&&method==='PATCH'){const input=JSON.parse(options.body);Object.entries(input).forEach(([key,value])=>state.settings[key]={...state.settings[key],...value});return answer({data:input});}
  if(path==='/billing/policy'&&method==='GET')return answer({data:state.settings.billing});
  if(/^\/patients\/[^/]+\/clinical-records$/.test(path)&&method==='GET'){const patientId=path.split('/')[2];return answer({data:state.clinicalRecords.filter(x=>x.patient_id===patientId)});}
  if(/^\/patients\/[^/]+\/clinical-records$/.test(path)&&method==='POST'){const patientId=path.split('/')[2],input=JSON.parse(options.body),item={id:`rec_${state.clinicalRecords.length+1}`,patient_id:patientId,professional_name:'Carolina Martins',version:state.clinicalRecords.filter(x=>x.patient_id===patientId&&x.type===input.type).length+1,created_at:new Date().toISOString(),...input};state.clinicalRecords.push(item);return answer({data:item},201);}
  if(/^\/patients\/[^/]+\/psychological-documents$/.test(path)&&method==='GET'){const patientId=path.split('/')[2];return answer({data:state.psychologicalDocuments.filter(x=>x.patient_id===patientId)});}
  if(/^\/patients\/[^/]+\/psychological-documents$/.test(path)&&method==='POST'){const patientId=path.split('/')[2],input=JSON.parse(options.body),item={id:`doc_${state.psychologicalDocuments.length+1}`,patient_id:patientId,number:`${input.type==='certificate'?'ATE':'ORI'}-2026-000001`,verification_code:'VERIFY1234567890',status:input.issue?'issued':'draft',issued_at:input.issue?new Date().toISOString():null,created_at:new Date().toISOString(),...input};state.psychologicalDocuments.push(item);return answer({data:item},201);}
  if(/^\/psychological-documents\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.psychologicalDocuments.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);item.status=input.action==='issue'?'issued':'cancelled';return answer({data:item});}
  if(path==='/inventory/summary'&&method==='GET')return answer({data:{items:state.inventory.filter(x=>x.active).length,value_cents:state.inventory.reduce((sum,x)=>sum+x.quantity*x.unit_cost_cents,0),low_stock:state.inventory.filter(x=>x.active&&x.quantity<=x.minimum_quantity).length,out_of_stock:state.inventory.filter(x=>x.active&&x.quantity===0).length,movements_30d:state.inventoryMovements.length}});
  if(path==='/inventory'&&method==='GET')return answer({data:state.inventory});
  if(path==='/inventory'&&method==='POST'){const input=JSON.parse(options.body),item={id:`stk_${state.inventory.length+1}`,...input,quantity:Number(input.quantity),minimum_quantity:Number(input.minimum_quantity),unit_cost_cents:Math.round(input.unit_cost*100),active:1,unit_name:state.units.find(x=>x.id===input.unit_id)?.name,created_at:new Date().toISOString()};state.inventory.push(item);if(item.quantity)state.inventoryMovements.push({id:'mov_initial',item_id:item.id,type:'in',quantity:item.quantity,balance_after:item.quantity,reason:'Estoque inicial',created_at:new Date().toISOString()});return answer({data:item},201);}
  if(/^\/inventory\/[^/]+\/movements$/.test(path)&&method==='GET'){const id=path.split('/')[2];return answer({data:state.inventoryMovements.filter(x=>x.item_id===id)});}
  if(/^\/inventory\/[^/]+\/movements$/.test(path)&&method==='POST'){const id=path.split('/')[2],item=state.inventory.find(x=>x.id===id),input=JSON.parse(options.body),next=input.type==='adjustment'?input.quantity:input.type==='in'?item.quantity+input.quantity:item.quantity-input.quantity;if(next<0)return answer({error:'Estoque insuficiente'},409);const movement={id:`mov_${state.inventoryMovements.length+1}`,item_id:id,...input,quantity:input.type==='adjustment'?next-item.quantity:input.quantity,balance_after:next,created_at:new Date().toISOString()};item.quantity=next;state.inventoryMovements.push(movement);return answer({data:movement},201);}
  if(/^\/inventory\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.inventory.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);if(input.unit_cost!==undefined)item.unit_cost_cents=Math.round(input.unit_cost*100);return answer({data:item});}
  if(path.startsWith('/rooms')&&method==='GET')return answer({data:state.rooms});
  if(path==='/rooms'&&method==='POST'){const input=JSON.parse(options.body),room={id:`rom_${state.rooms.length+1}`,...input,unit_name:state.units.find(x=>x.id===input.unit_id)?.name,active:true,equipment_count:0,maintenance_count:0};state.rooms.push(room);return answer({data:room},201);}
  if(path.startsWith('/equipment')&&method==='GET')return answer({data:state.equipment});
  if(path==='/equipment'&&method==='POST'){const input=JSON.parse(options.body),item={id:`eqp_${state.equipment.length+1}`,...input,status:'available'};state.equipment.push(item);return answer({data:item},201);}
  if(path.startsWith('/maintenance')&&method==='GET')return answer({data:state.maintenance});
  if(path==='/maintenance'&&method==='POST'){const input=JSON.parse(options.body),item={id:`mnt_${state.maintenance.length+1}`,...input,status:'scheduled',cost_cents:Math.round(Number(input.cost)*100),equipment_name:state.equipment.find(x=>x.id===input.equipment_id)?.name};state.maintenance.push(item);return answer({data:item},201);}
  if(path==='/suppliers'&&method==='GET')return answer({data:state.suppliers});
  if(path==='/suppliers'&&method==='POST'){const input=JSON.parse(options.body),item={id:`sup_${state.suppliers.length+1}`,...input,active:1,created_at:new Date().toISOString()};state.suppliers.push(item);return answer({data:item},201);}
  if(path==='/payables/summary'&&method==='GET'){const active=state.payables.filter(x=>x.status!=='cancelled'),pending=active.filter(x=>x.status==='pending'),paid=active.filter(x=>x.status==='paid');return answer({data:{month:'2026-08',paid_cents:paid.reduce((s,x)=>s+x.amount_cents,0),pending_cents:pending.reduce((s,x)=>s+x.amount_cents,0),overdue_cents:0,overdue_count:0,total:active.length}});}
  if(path==='/payables'&&method==='GET')return answer({data:state.payables});
  if(path==='/payables'&&method==='POST'){const input=JSON.parse(options.body),created=[];for(let i=0;i<input.installments;i++){const item={id:`pay_${state.payables.length+1}`,...input,amount_cents:Math.round(input.amount*100),installment_number:i+1,installment_total:input.installments,status:'pending',effective_status:'pending',supplier_name:state.suppliers.find(x=>x.id===input.supplier_id)?.name,unit_name:state.units.find(x=>x.id===input.unit_id)?.name,created_at:new Date().toISOString()};state.payables.push(item);created.push(item);}return answer({data:created},201);}
  if(/^\/payables\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.payables.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);if(input.action==='pay'){item.status=item.effective_status='paid';item.paid_at=input.paid_at;state.finance.push({id:`finance_${state.finance.length+1}`,description:`Conta paga · ${item.description}`,type:'expense',amount_cents:item.amount_cents,status:'paid',created_at:new Date().toISOString()});}if(input.action==='cancel')item.status=item.effective_status='cancelled';return answer({data:item});}
  if(path==='/receipts/summary'&&method==='GET'){const issued=state.receipts.filter(x=>x.status==='issued');return answer({data:{year:'2026',total:state.receipts.length,issued:issued.length,cancelled:state.receipts.length-issued.length,amount_cents:issued.reduce((s,x)=>s+x.amount_cents,0)}});}
  if(path==='/receipts'&&method==='GET')return answer({data:state.receipts});
  if(path==='/receipts'&&method==='POST'){const input=JSON.parse(options.body),patient=state.patients.find(x=>x.id===input.patient_id),payment=state.finance.find(x=>x.id===input.financial_entry_id),item={id:`rcp_${state.receipts.length+1}`,...input,number:`REC-2026-${String(state.receipts.length+1).padStart(6,'0')}`,verification_code:'TESTCODE12345678',patient_name:patient.name,description:input.description||payment?.description,amount_cents:payment?.amount_cents||Math.round(input.amount*100),payment_date:input.payment_date||'2026-08-05',issued_at:new Date().toISOString(),status:'issued',clinic_name:'Psyché Saúde'};state.receipts.push(item);return answer({data:item},201);}
  if(/^\/receipts\/[^/]+$/.test(path)&&method==='GET'){const item=state.receipts.find(x=>x.id===path.split('/').at(-1));return answer({data:{...item,clinic_name:'Psyché Saúde',issued_by:'Carolina Martins'}});}
  if(/^\/receipts\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.receipts.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);item.status='cancelled';item.cancellation_reason=input.cancellation_reason;return answer({data:item});}
  if(path==='/invoices/summary')return answer({data:{year:'2026',total:state.invoices.length,authorized:state.invoices.filter(x=>x.status==='authorized').length,pending:state.invoices.filter(x=>['draft','processing'].includes(x.status)).length,cancelled:0,amount_cents:0}});
  if(path==='/invoices'&&method==='GET')return answer({data:state.invoices});
  if(path==='/invoices'&&method==='POST'){const d=JSON.parse(options.body),p=state.patients.find(x=>x.id===d.patient_id),x={id:`nfs_${state.invoices.length+1}`,...d,internal_number:`NFS-2026-${String(state.invoices.length+1).padStart(6,'0')}`,patient_name:p.name,amount_cents:Math.round(d.amount*100),status:'draft',created_at:new Date().toISOString()};state.invoices.push(x);return answer({data:x},201);}
  const maps={'/patients':'patients','/appointments':'appointments','/finance':'finance','/team':'team','/units':'units','/services':'services','/campaigns':'campaigns','/conversations':'conversations'};
  if(method==='GET'&&maps[path])return answer({data:state[maps[path]]});
  if(method==='POST'&&maps[path]){const input=JSON.parse(options.body),key=maps[path],existing=key==='conversations'?state.conversations.find(x=>x.patient_id===input.patient_id):null;if(existing)return answer({data:existing},201);const item={id:`${key}_${state[key].length+1}`,...input};if(key==='patients')item.status='active';if(key==='appointments'){item.status='confirmed';item.patient_name=state.patients.find(x=>x.id===item.patient_id)?.name;item.professional_name=state.user.name;}if(key==='finance'){item.amount_cents=Math.round(item.amount*100);item.created_at=new Date().toISOString();}if(key==='team')item.active=1;if(key==='services'){item.price_cents=Math.round(item.price*100);item.active=1;item.created_at=new Date().toISOString();}if(key==='campaigns'){item.status='draft';item.created_at=new Date().toISOString();}if(key==='conversations'){item.patient_name=state.patients.find(x=>x.id===item.patient_id)?.name;item.created_at=new Date().toISOString();}state[key].push(item);return answer({data:item},201);}
  if(path.endsWith('/read')&&method==='PATCH'){state.messages.filter(x=>x.sender_type==='patient').forEach(x=>x.read_at=new Date().toISOString());return answer(null,204);}
  if(path.includes('/messages')){if(method==='GET')return answer({data:state.messages});const input=JSON.parse(options.body),item={id:`msg_${state.messages.length+1}`,sender_type:'staff',body:input.body,created_at:new Date().toISOString()};state.messages.push(item);return answer({data:item},201);}
  if(/^\/patients\/[^/]+$/.test(path)&&method==='GET'){const item=state.patients.find(x=>x.id===path.split('/').at(-1));return answer({data:{...item,professional_name:'Carolina Martins',profile:{occupation:'Designer',emergency_name:'José Costa',emergency_phone:'11988887777',address:'São Paulo'},appointments:state.appointments,clinical_sessions:[],finance:{paid_cents:30000,pending_cents:5000},consents:state.consents||[],documents:[]}});}
  if(/^\/patients\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.patients.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);return answer({data:item});}
  if(/^\/patients\/[^/]+$/.test(path)&&method==='DELETE'){const item=state.patients.find(x=>x.id===path.split('/').at(-1));item.status='archived';return answer(null,204);}
  if(/^\/finance\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.finance.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);if(input.amount!==undefined)item.amount_cents=Math.round(input.amount*100);return answer({data:item});}
  if(/^\/finance\/[^/]+$/.test(path)&&method==='DELETE'){const item=state.finance.find(x=>x.id===path.split('/').at(-1));item.status='void';return answer(null,204);}
  if(/^\/campaigns\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.campaigns.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);return answer({data:item});}
  if(/^\/campaigns\/[^/]+$/.test(path)&&method==='DELETE'){const item=state.campaigns.find(x=>x.id===path.split('/').at(-1));item.status='archived';return answer(null,204);}
  if(/^\/units\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.units.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);return answer({data:item});}
  if(/^\/services\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.services.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);if(input.price!==undefined)item.price_cents=Math.round(input.price*100);return answer({data:item});}
  if(path.endsWith('/consents')&&method==='POST'){const input=JSON.parse(options.body);state.consents??=[];const item={id:'cns_1',...input,accepted_at:new Date().toISOString()};state.consents.push(item);return answer({data:item},201);}
  if(/^\/team\/[^/]+$/.test(path)&&method==='GET'){const item=state.team.find(x=>x.id===path.split('/').at(-1));const rolePermissions={admin:['*'],professional:['patients:read','appointments:write','sessions:read'],reception:['patients:read','appointments:write'],finance:['finance:read','finance:write']};return answer({data:{...item,permissions:rolePermissions[item.role],activity:[]}});}
  if(/^\/team\/[^/]+$/.test(path)&&method==='PATCH'){const item=state.team.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);return answer({data:item});}
  if(path.endsWith('/reset-password')&&method==='POST')return answer(null,204);
  if(path.startsWith('/appointments/')&&method==='PATCH'){const item=state.appointments.find(x=>x.id===path.split('/').at(-1)),input=JSON.parse(options.body);Object.assign(item,input);return answer({data:item});}
  if(path.startsWith('/appointments/')&&method==='DELETE'){const item=state.appointments.find(x=>x.id===path.split('/').at(-1));item.status='cancelled';return answer(null,204);}
  if(path==='/clinical-sessions'&&method==='POST')return answer({data:{id:'cls_1'}},201);
  if(/^\/clinical-sessions\/[^/]+$/.test(path)&&method==='PATCH')return answer({data:{id:path.split('/').at(-1),updated_at:new Date().toISOString()}});
  return answer({error:'Rota simulada não encontrada'},404);
});
