import {beforeAll,describe,expect,it,vi} from 'vitest';

beforeAll(async()=>{await import('../app.js');await vi.waitFor(()=>expect(document.querySelector('#teamRows').textContent).toContain('Gustavo Lima'));});

describe('Equipe e permissões SaaS',()=>{
  it('renders team indicators and role information',()=>{expect(document.querySelector('#teamActive').textContent).toBe('2');expect(document.querySelector('#teamProfessionals').textContent).toBe('1');expect(document.querySelector('#teamAdmins').textContent).toBe('1');});
  it('filters team members through the API',async()=>{const role=document.querySelector('#teamRole');role.value='professional';role.dispatchEvent(new Event('change'));await vi.waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('role=professional'),expect.anything()));});
  it('opens a member profile with server-side permissions',async()=>{document.querySelector('[data-team-id="usr_2"]').click();await vi.waitFor(()=>expect(document.querySelector('#teamProfile').open).toBe(true));await vi.waitFor(()=>expect(document.querySelector('#teamProfileContent').textContent).toContain('Permissões deste perfil'));expect(document.querySelector('#teamProfileContent').textContent).toContain('Visualizar pacientes');});
  it('configures weekly availability by unit and consulting room',async()=>{await vi.waitFor(()=>expect(document.querySelector('[data-team-schedule]')).toBeTruthy());document.querySelector('[data-team-schedule]').click();await vi.waitFor(()=>expect(document.querySelector('#scheduleDialog').open).toBe(true));const form=document.querySelector('#scheduleForm');form.elements.day_1.checked=true;form.elements.unit_1.value='unt_1';form.elements.room_1.value='Consultório 1';form.elements.opens_1.value='08:00';form.elements.closes_1.value='17:00';form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await vi.waitFor(()=>expect(globalThis.__apiState.scheduleRules.professionals.usr_2).toHaveLength(1));expect(globalThis.__apiState.scheduleRules.professionals.usr_2[0].room).toBe('Consultório 1');});
  it('edits and suspends a team member',async()=>{const form=document.querySelector('#teamEditForm');form.elements.name.value='Gustavo Lima Silva';form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await vi.waitFor(()=>expect(globalThis.__apiState.team[1].name).toBe('Gustavo Lima Silva'));await vi.waitFor(()=>expect(document.querySelector('#teamProfile').open).toBe(false));window.dispatchEvent(new Event('psyche:refresh'));await vi.waitFor(()=>expect(document.querySelector('[data-team-id="usr_2"]')).toBeTruthy());document.querySelector('[data-team-id="usr_2"]').click();await vi.waitFor(()=>expect(document.querySelector('#toggleMember')).toBeTruthy());document.querySelector('#toggleMember').click();await vi.waitFor(()=>expect(globalThis.__apiState.team[1].active).toBe(false));});
  it('renders the RBAC matrix from backend role definitions',async()=>{document.querySelector('.permissions-btn').click();expect(document.querySelector('#utilityDialog').open).toBe(true);expect(document.querySelector('.rbac-matrix').textContent).toContain('Administrador');expect(document.querySelector('.rbac-matrix').textContent).toContain('Financeiro');});
});
