CREATE TABLE plans (
  key text PRIMARY KEY,
  name text NOT NULL,
  modules_json jsonb NOT NULL,
  limits_json jsonb NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL
);

CREATE TABLE clinics (id text PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE clinic_subscriptions (
  clinic_id text PRIMARY KEY REFERENCES clinics(id),
  plan_key text NOT NULL REFERENCES plans(key),
  status text NOT NULL CHECK(status IN ('trialing','active','past_due','suspended','cancelled')),
  trial_ends_at timestamptz,
  current_period_ends_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE TABLE units (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),name text NOT NULL,address text,rooms integer NOT NULL DEFAULT 1,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL);
CREATE TABLE users (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),unit_id text REFERENCES units(id),name text NOT NULL,email text NOT NULL UNIQUE,password_hash text NOT NULL,role text NOT NULL CHECK(role IN ('admin','professional','reception','finance')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL);
CREATE TABLE clinic_module_overrides (clinic_id text NOT NULL REFERENCES clinics(id),module_key text NOT NULL,enabled boolean NOT NULL,reason text,updated_by text REFERENCES users(id),updated_at timestamptz NOT NULL,PRIMARY KEY(clinic_id,module_key));
CREATE TABLE sessions (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE patients (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),professional_id text REFERENCES users(id),name text NOT NULL,email text,phone text,cpf_encrypted text,birth_date date,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE patient_users (patient_id text PRIMARY KEY REFERENCES patients(id),email text NOT NULL UNIQUE,password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,last_login timestamptz,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE patient_sessions (id text PRIMARY KEY,patient_id text NOT NULL REFERENCES patients(id),token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE patient_profiles (patient_id text PRIMARY KEY REFERENCES patients(id),clinic_id text NOT NULL REFERENCES clinics(id),gender text,occupation text,emergency_name_encrypted text,emergency_phone_encrypted text,address_encrypted text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE patient_consents (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),type text NOT NULL,accepted boolean NOT NULL DEFAULT false,accepted_at timestamptz,expires_at timestamptz,created_at timestamptz NOT NULL);
CREATE TABLE patient_documents (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),name text NOT NULL,mime_type text NOT NULL,storage_key text NOT NULL,size_bytes bigint NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE appointments (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),unit_id text REFERENCES units(id),patient_id text NOT NULL REFERENCES patients(id),professional_id text NOT NULL REFERENCES users(id),starts_at timestamptz NOT NULL,duration_minutes integer NOT NULL DEFAULT 50,modality text NOT NULL,room text,status text NOT NULL DEFAULT 'confirmed',created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,booking_type text NOT NULL DEFAULT 'regular');
CREATE TABLE appointment_confirmations (appointment_id text PRIMARY KEY REFERENCES appointments(id),clinic_id text NOT NULL REFERENCES clinics(id),status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','reschedule_requested','declined')),requested_at timestamptz NOT NULL,responded_at timestamptz,response_note text,message_id text,reminder_count integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL);
CREATE TABLE appointment_events (id text PRIMARY KEY,appointment_id text NOT NULL REFERENCES appointments(id),clinic_id text NOT NULL REFERENCES clinics(id),actor_type text NOT NULL CHECK(actor_type IN ('staff','patient','system')),actor_id text,type text NOT NULL,details_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL);
CREATE TABLE unit_schedule_rules (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),unit_id text NOT NULL REFERENCES units(id),room text NOT NULL DEFAULT '',weekday integer NOT NULL CHECK(weekday BETWEEN 0 AND 6),opens_time time NOT NULL,closes_time time NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL,UNIQUE(unit_id,room,weekday,opens_time,closes_time));
CREATE TABLE professional_schedule_rules (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),professional_id text NOT NULL REFERENCES users(id),unit_id text NOT NULL REFERENCES units(id),room text NOT NULL DEFAULT '',weekday integer NOT NULL CHECK(weekday BETWEEN 0 AND 6),opens_time time NOT NULL,closes_time time NOT NULL,slot_minutes integer NOT NULL DEFAULT 50,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL,UNIQUE(professional_id,unit_id,room,weekday,opens_time,closes_time));
CREATE TABLE professional_availability (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),professional_id text NOT NULL REFERENCES users(id),unit_id text REFERENCES units(id),opens_at timestamptz NOT NULL,closes_at timestamptz NOT NULL,slot_minutes integer NOT NULL DEFAULT 50,active boolean NOT NULL DEFAULT true,created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL);
CREATE TABLE conversations (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),created_at timestamptz NOT NULL);
CREATE TABLE messages (id text PRIMARY KEY,conversation_id text NOT NULL REFERENCES conversations(id),sender_type text NOT NULL,sender_id text NOT NULL,body_encrypted text NOT NULL,created_at timestamptz NOT NULL,read_at timestamptz);
ALTER TABLE appointment_confirmations ADD CONSTRAINT appointment_confirmation_message_fk FOREIGN KEY(message_id) REFERENCES messages(id);
CREATE TABLE clinical_sessions (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),appointment_id text REFERENCES appointments(id),patient_id text NOT NULL REFERENCES patients(id),professional_id text NOT NULL REFERENCES users(id),started_at timestamptz NOT NULL,finished_at timestamptz,duration_seconds integer NOT NULL DEFAULT 0,notes_encrypted text,sud_history_encrypted text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE clinical_records (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),professional_id text NOT NULL REFERENCES users(id),session_id text REFERENCES clinical_sessions(id),type text NOT NULL CHECK(type IN ('anamnesis','case_plan','evolution','referral','closure')),title text NOT NULL,content_encrypted text NOT NULL,visibility text NOT NULL DEFAULT 'record' CHECK(visibility IN ('record','restricted')),status text NOT NULL DEFAULT 'active' CHECK(status IN ('draft','active','completed','archived')),version integer NOT NULL DEFAULT 1,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE psychological_documents (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),professional_id text NOT NULL REFERENCES users(id),type text NOT NULL CHECK(type IN ('certificate','guidance')),number text NOT NULL,verification_code text NOT NULL UNIQUE,title text NOT NULL,recipient text,purpose text NOT NULL,content_encrypted text NOT NULL,professional_name text NOT NULL,professional_registration text NOT NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','issued','cancelled')),issued_at timestamptz,cancelled_at timestamptz,cancellation_reason text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(clinic_id,number));
CREATE TABLE services (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),name text NOT NULL,duration_minutes integer NOT NULL,price_cents bigint NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL);
CREATE TABLE clinic_settings (clinic_id text NOT NULL REFERENCES clinics(id),key text NOT NULL,value_json jsonb NOT NULL,updated_at timestamptz NOT NULL,PRIMARY KEY(clinic_id,key));
CREATE TABLE financial_entries (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text REFERENCES patients(id),appointment_id text REFERENCES appointments(id),description text NOT NULL,type text NOT NULL CHECK(type IN ('income','expense')),amount_cents bigint NOT NULL,due_date date,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL);
CREATE TABLE suppliers (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),name text NOT NULL,document text,email text,phone text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL);
CREATE TABLE accounts_payable (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),supplier_id text REFERENCES suppliers(id),unit_id text REFERENCES units(id),financial_entry_id text REFERENCES financial_entries(id),description text NOT NULL,category text NOT NULL,amount_cents bigint NOT NULL,due_date date,paid_at timestamptz,status text NOT NULL DEFAULT 'pending',installment_number integer NOT NULL DEFAULT 1,installment_total integer NOT NULL DEFAULT 1,recurrence text,notes text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE receipts (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),financial_entry_id text REFERENCES financial_entries(id),number text NOT NULL,verification_code text NOT NULL UNIQUE,patient_name text NOT NULL,patient_document text,description text NOT NULL,amount_cents bigint NOT NULL,payment_date date NOT NULL,issued_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'issued',cancelled_at timestamptz,cancellation_reason text,created_by text NOT NULL REFERENCES users(id),updated_at timestamptz NOT NULL,UNIQUE(clinic_id,number));
CREATE TABLE fiscal_invoices (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text NOT NULL REFERENCES patients(id),financial_entry_id text REFERENCES financial_entries(id),receipt_id text REFERENCES receipts(id),internal_number text NOT NULL,external_number text,provider text,external_id text,verification_url text,patient_name text NOT NULL,patient_document text,service_code text NOT NULL,description text NOT NULL,amount_cents bigint NOT NULL,issued_at timestamptz,status text NOT NULL DEFAULT 'draft',error_message text,cancelled_at timestamptz,cancellation_reason text,created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(clinic_id,internal_number));
CREATE TABLE inventory_items (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),unit_id text REFERENCES units(id),name text NOT NULL,sku text,category text NOT NULL,unit_measure text NOT NULL,quantity numeric(14,3) NOT NULL DEFAULT 0,minimum_quantity numeric(14,3) NOT NULL DEFAULT 0,unit_cost_cents bigint NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE inventory_movements (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),item_id text NOT NULL REFERENCES inventory_items(id),user_id text NOT NULL REFERENCES users(id),type text NOT NULL CHECK(type IN ('in','out','adjustment')),quantity numeric(14,3) NOT NULL,balance_after numeric(14,3) NOT NULL,reason text NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE campaigns (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),name text NOT NULL,channel text NOT NULL,audience text NOT NULL,status text NOT NULL DEFAULT 'draft',created_at timestamptz NOT NULL);
CREATE TABLE feedback (id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),patient_id text REFERENCES patients(id),appointment_id text REFERENCES appointments(id),score integer NOT NULL CHECK(score BETWEEN 1 AND 5),comment_encrypted text,created_at timestamptz NOT NULL);
CREATE TABLE audit_log (id text PRIMARY KEY,clinic_id text,user_id text,action text NOT NULL,entity text NOT NULL,entity_id text,metadata jsonb,ip text,created_at timestamptz NOT NULL);

CREATE INDEX idx_appointments_clinic_start ON appointments(clinic_id,starts_at);
CREATE INDEX idx_patients_clinic_name ON patients(clinic_id,name);
CREATE INDEX idx_finance_clinic_created ON financial_entries(clinic_id,created_at);
CREATE INDEX idx_audit_clinic_created ON audit_log(clinic_id,created_at);
CREATE INDEX idx_clinical_records_patient ON clinical_records(clinic_id,patient_id,type,created_at);
CREATE INDEX idx_messages_conversation_created ON messages(conversation_id,created_at);
