CREATE TABLE clinic_rooms(id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),unit_id text NOT NULL REFERENCES units(id),name text NOT NULL,capacity integer NOT NULL DEFAULT 1,kind text NOT NULL DEFAULT 'consulting',features jsonb NOT NULL DEFAULT '[]',active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE room_equipment(id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),room_id text NOT NULL REFERENCES clinic_rooms(id),name text NOT NULL,asset_tag text,serial_number text,status text NOT NULL DEFAULT 'available' CHECK(status IN('available','in_use','maintenance','retired')),purchased_at date,warranty_until date,notes text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE equipment_maintenance(id text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id),equipment_id text NOT NULL REFERENCES room_equipment(id),type text NOT NULL,description text NOT NULL,status text NOT NULL DEFAULT 'scheduled' CHECK(status IN('scheduled','in_progress','completed','cancelled')),scheduled_for date,completed_at timestamptz,cost_cents bigint NOT NULL DEFAULT 0,created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_rooms_unit ON clinic_rooms(unit_id,active);
CREATE INDEX idx_equipment_room ON room_equipment(room_id,status);
CREATE INDEX idx_maintenance_equipment ON equipment_maintenance(equipment_id,status,scheduled_for);
ALTER TABLE clinic_rooms ENABLE ROW LEVEL SECURITY;ALTER TABLE clinic_rooms FORCE ROW LEVEL SECURITY;CREATE POLICY tenant_isolation ON clinic_rooms USING(clinic_id=current_tenant_id()) WITH CHECK(clinic_id=current_tenant_id());
ALTER TABLE room_equipment ENABLE ROW LEVEL SECURITY;ALTER TABLE room_equipment FORCE ROW LEVEL SECURITY;CREATE POLICY tenant_isolation ON room_equipment USING(clinic_id=current_tenant_id()) WITH CHECK(clinic_id=current_tenant_id());
ALTER TABLE equipment_maintenance ENABLE ROW LEVEL SECURITY;ALTER TABLE equipment_maintenance FORCE ROW LEVEL SECURITY;CREATE POLICY tenant_isolation ON equipment_maintenance USING(clinic_id=current_tenant_id()) WITH CHECK(clinic_id=current_tenant_id());
