import{postgresPool,withTenant}from'./db/postgres.js';

const safeUser=`u.id,u.name,u.email,u.role,u.unit_id,u.active,u.created_at,un.name unit_name,(SELECT MAX(s.created_at) FROM sessions s WHERE s.user_id=u.id) last_login`;

export function postgresAdminStore(pool=postgresPool()){return{kind:'postgres',
  async team(clinicId,filters={}){return withTenant(pool,clinicId,async client=>{const conditions=['u.clinic_id=$1'],values=[clinicId];if(filters.q){values.push(`%${filters.q.slice(0,80)}%`);conditions.push(`(u.name ILIKE $${values.length} OR u.email ILIKE $${values.length})`);}for(const[key,column]of[['role','u.role'],['unitId','u.unit_id']])if(filters[key]){values.push(filters[key]);conditions.push(`${column}=$${values.length}`);}if(filters.active!==undefined){values.push(Boolean(filters.active));conditions.push(`u.active=$${values.length}`);}return(await client.query(`SELECT ${safeUser} FROM users u LEFT JOIN units un ON un.id=u.unit_id WHERE ${conditions.join(' AND ')} ORDER BY u.active DESC,u.name`,values)).rows;});},
  async member(clinicId,id){return withTenant(pool,clinicId,async client=>(await client.query(`SELECT ${safeUser} FROM users u LEFT JOIN units un ON un.id=u.unit_id WHERE u.id=$1 AND u.clinic_id=$2`,[id,clinicId])).rows[0]||null);},
  async createUser(clinicId,user){return withTenant(pool,clinicId,async client=>{if(user.unitId&&!((await client.query('SELECT id FROM units WHERE id=$1 AND clinic_id=$2 AND active=true',[user.unitId,clinicId])).rows[0]))throw Object.assign(new Error('Unidade inválida'),{status:400});return(await client.query(`INSERT INTO users(id,clinic_id,unit_id,name,email,password_hash,role,active,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,true,$8) RETURNING id,name,email,role,unit_id,active,created_at`,[user.id,clinicId,user.unitId,user.name,user.email,user.passwordHash,user.role,user.createdAt])).rows[0];});},
  async removeUser(clinicId,id){return withTenant(pool,clinicId,client=>client.query('DELETE FROM users WHERE id=$1 AND clinic_id=$2',[id,clinicId]));},
  async updateUser(clinicId,id,change){return withTenant(pool,clinicId,async client=>{const current=(await client.query('SELECT * FROM users WHERE id=$1 AND clinic_id=$2 FOR UPDATE',[id,clinicId])).rows[0];if(!current)return null;if(change.unitId&&!((await client.query('SELECT id FROM units WHERE id=$1 AND clinic_id=$2 AND active=true',[change.unitId,clinicId])).rows[0]))throw Object.assign(new Error('Unidade inválida'),{status:400});if(current.role==='admin'&&current.active&&(change.role!=='admin'||!change.active)){const count=Number((await client.query("SELECT COUNT(*) total FROM users WHERE clinic_id=$1 AND role='admin' AND active=true AND id!=$2",[clinicId,id])).rows[0].total);if(count===0)throw Object.assign(new Error('A clínica deve manter pelo menos um administrador ativo'),{status:409});}return(await client.query('UPDATE users SET name=$3,email=$4,role=$5,unit_id=$6,active=$7 WHERE id=$1 AND clinic_id=$2 RETURNING id,name,email,role,unit_id,active,created_at',[id,clinicId,change.name,change.email,change.role,change.unitId,change.active])).rows[0];});},
  async resetPassword(clinicId,id,passwordHash){return withTenant(pool,clinicId,async client=>{const updated=(await client.query('UPDATE users SET password_hash=$3 WHERE id=$1 AND clinic_id=$2 RETURNING id',[id,clinicId,passwordHash])).rows[0];if(!updated)return false;await client.query('DELETE FROM sessions WHERE user_id=$1',[id]);return true;});},
  async units(clinicId){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM units WHERE clinic_id=$1 ORDER BY name',[clinicId])).rows);},
  async unit(clinicId,id){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM units WHERE id=$1 AND clinic_id=$2',[id,clinicId])).rows[0]||null);},
  async createUnit(clinicId,unit){return withTenant(pool,clinicId,async client=>(await client.query('INSERT INTO units(id,clinic_id,name,address,rooms,active,created_at) VALUES($1,$2,$3,$4,$5,true,$6) RETURNING *',[unit.id,clinicId,unit.name,unit.address,unit.rooms,unit.createdAt])).rows[0]);},
  async removeUnit(clinicId,id){return withTenant(pool,clinicId,client=>client.query('DELETE FROM units WHERE id=$1 AND clinic_id=$2',[id,clinicId]));},
  async updateUnit(clinicId,id,change){return withTenant(pool,clinicId,async client=>(await client.query('UPDATE units SET name=$3,address=$4,rooms=$5,active=$6 WHERE id=$1 AND clinic_id=$2 RETURNING *',[id,clinicId,change.name,change.address,change.rooms,change.active])).rows[0]||null);},
  async services(clinicId){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM services WHERE clinic_id=$1 ORDER BY active DESC,name',[clinicId])).rows);},
  async service(clinicId,id){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM services WHERE id=$1 AND clinic_id=$2',[id,clinicId])).rows[0]||null);},
  async createService(clinicId,service){return withTenant(pool,clinicId,async client=>(await client.query('INSERT INTO services(id,clinic_id,name,duration_minutes,price_cents,active,created_at) VALUES($1,$2,$3,$4,$5,true,$6) RETURNING *',[service.id,clinicId,service.name,service.duration,service.priceCents,service.createdAt])).rows[0]);},
  async removeService(clinicId,id){return withTenant(pool,clinicId,client=>client.query('DELETE FROM services WHERE id=$1 AND clinic_id=$2',[id,clinicId]));},
  async updateService(clinicId,id,change){return withTenant(pool,clinicId,async client=>(await client.query('UPDATE services SET name=$3,duration_minutes=$4,price_cents=$5,active=$6 WHERE id=$1 AND clinic_id=$2 RETURNING *',[id,clinicId,change.name,change.duration,change.priceCents,change.active])).rows[0]||null);},
  async settings(clinicId){return withTenant(pool,clinicId,async client=>(await client.query('SELECT key,value_json FROM clinic_settings WHERE clinic_id=$1',[clinicId])).rows);},
  async saveSettings(clinicId,entries){return withTenant(pool,clinicId,async client=>{for(const entry of entries)await client.query('INSERT INTO clinic_settings(clinic_id,key,value_json,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(clinic_id,key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at',[clinicId,entry.key,entry.value,entry.updatedAt]);return entries;});},
  async appendAudit(event){if(!event.clinicId)return null;return withTenant(pool,event.clinicId,async client=>(await client.query('INSERT INTO audit_log(id,clinic_id,user_id,action,entity,entity_id,metadata,ip,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING RETURNING id',[event.id,event.clinicId,event.userId,event.action,event.entity,event.entityId,event.metadata,event.ip,event.createdAt])).rows[0]||null);},
  async audit(clinicId,{limit=500}={}){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM audit_log WHERE clinic_id=$1 ORDER BY created_at DESC LIMIT $2',[clinicId,Math.min(Math.max(Number(limit)||500,1),1000)])).rows);},
  async userActivity(clinicId,userId){return withTenant(pool,clinicId,async client=>(await client.query('SELECT id,action,entity,entity_id,created_at FROM audit_log WHERE user_id=$1 AND clinic_id=$2 ORDER BY created_at DESC LIMIT 30',[userId,clinicId])).rows);},
  async setting(clinicId,key){return withTenant(pool,clinicId,async client=>(await client.query('SELECT key,value_json FROM clinic_settings WHERE clinic_id=$1 AND key=$2',[clinicId,key])).rows[0]||null);},
  close(){return pool.end();}
};}
