import { postgresPool, withTenant } from './db/postgres.js';
import { moduleCatalog } from './modules.js';

export function postgresAuthStore(pool=postgresPool()){
  return{
    kind:'postgres',
    async health(){const{rows}=await pool.query('SELECT 1 AS connected');return rows[0]?.connected===1;},
    async findUser(email){const{rows}=await pool.query('SELECT * FROM psyche_login_identity($1)',[email]);return rows[0]||null;},
    async userByToken(tokenHash,now){const{rows}=await pool.query('SELECT * FROM psyche_session_identity($1,$2)',[tokenHash,now]);return rows[0]||null;},
    async sessionTimeout(clinicId){return withTenant(pool,clinicId,async client=>{const{rows}=await client.query("SELECT value_json FROM clinic_settings WHERE clinic_id=$1 AND key='security'",[clinicId]);return Number(rows[0]?.value_json?.session_timeout_minutes)||480;});},
    async createSession({id,userId,clinicId,tokenHash,expiresAt,createdAt}){return withTenant(pool,clinicId,client=>client.query('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES ($1,$2,$3,$4,$5)',[id,userId,tokenHash,expiresAt,createdAt]));},
    async deleteExpired(clinicId,now){return withTenant(pool,clinicId,client=>client.query('DELETE FROM sessions WHERE expires_at<=$1',[now]));},
    async deleteSession(tokenHash,clinicId){if(!clinicId)return;return withTenant(pool,clinicId,client=>client.query('DELETE FROM sessions WHERE token_hash=$1',[tokenHash]));},
    async context(clinicId){return withTenant(pool,clinicId,async client=>{const{rows}=await client.query(`SELECT c.id,c.name,c.created_at,cs.plan_key,cs.status,cs.trial_ends_at,cs.current_period_ends_at,p.name plan_name,p.modules_json,p.limits_json FROM clinics c JOIN clinic_subscriptions cs ON cs.clinic_id=c.id JOIN plans p ON p.key=cs.plan_key WHERE c.id=$1`,[clinicId]);const row=rows[0];if(!row)return null;const enabled=new Set(row.modules_json||[]),overrides=(await client.query('SELECT module_key,enabled FROM clinic_module_overrides WHERE clinic_id=$1',[clinicId])).rows;overrides.forEach(item=>item.enabled?enabled.add(item.module_key):enabled.delete(item.module_key));const counts=await Promise.all([client.query('SELECT COUNT(*)::int total FROM users WHERE clinic_id=$1 AND active=true',[clinicId]),client.query('SELECT COUNT(*)::int total FROM units WHERE clinic_id=$1 AND active=true',[clinicId]),client.query("SELECT COUNT(*)::int total FROM patients WHERE clinic_id=$1 AND status!='archived'",[clinicId])]);return{tenant:{id:row.id,name:row.name,created_at:row.created_at},subscription:{plan_key:row.plan_key,plan_name:row.plan_name,status:row.status,trial_ends_at:row.trial_ends_at,current_period_ends_at:row.current_period_ends_at},modules:Object.fromEntries(Object.entries(moduleCatalog).map(([key,value])=>[key,{...value,enabled:enabled.has(key)}])),limits:row.limits_json||{},usage:{users:counts[0].rows[0].total,units:counts[1].rows[0].total,patients:counts[2].rows[0].total}};});},
    async subscriptionCatalog(){const{rows}=await pool.query(`SELECT key,name,description,monthly_price_cents,yearly_price_cents,currency,modules_json,limits_json FROM plans WHERE active=true AND monthly_price_cents IS NOT NULL ORDER BY monthly_price_cents`);return rows;},
    async subscriptionOverview(clinicId){return withTenant(pool,clinicId,async client=>{const subscription=(await client.query(`SELECT cs.plan_key,cs.status,cs.billing_cycle,cs.trial_ends_at,cs.current_period_ends_at,cs.cancel_at_period_end,cs.cancelled_at,cs.provider,p.name plan_name,p.monthly_price_cents,p.yearly_price_cents,p.currency FROM clinic_subscriptions cs JOIN plans p ON p.key=cs.plan_key WHERE cs.clinic_id=$1`,[clinicId])).rows[0];if(!subscription)return null;const[invoices,requests]=await Promise.all([client.query(`SELECT id,amount_cents,currency,status,due_at,paid_at,created_at FROM subscription_invoices WHERE clinic_id=$1 ORDER BY created_at DESC LIMIT 24`,[clinicId]),client.query(`SELECT id,request_type,from_plan_key,to_plan_key,billing_cycle,reason,effective_at,status,created_at FROM subscription_change_requests WHERE clinic_id=$1 ORDER BY created_at DESC LIMIT 20`,[clinicId])]);return{subscription,invoices:invoices.rows,requests:requests.rows};});},
    async requestSubscriptionChange(clinicId,userId,request){return withTenant(pool,clinicId,async client=>{const current=(await client.query('SELECT plan_key,status,current_period_ends_at FROM clinic_subscriptions WHERE clinic_id=$1 FOR UPDATE',[clinicId])).rows[0];if(!current)throw Object.assign(new Error('Assinatura não encontrada'),{status:404});const pending=(await client.query("SELECT id FROM subscription_change_requests WHERE clinic_id=$1 AND status='pending' LIMIT 1",[clinicId])).rows[0];if(pending)throw Object.assign(new Error('Já existe uma solicitação de assinatura em análise'),{status:409});if(request.type==='change_plan'){const target=(await client.query('SELECT key,limits_json FROM plans WHERE key=$1 AND active=true AND monthly_price_cents IS NOT NULL',[request.planKey])).rows[0];if(!target)throw Object.assign(new Error('Plano comercial indisponível'),{status:400});if(target.key===current.plan_key)throw Object.assign(new Error('O plano selecionado já é o plano atual'),{status:409});const counts=(await Promise.all([client.query('SELECT COUNT(*)::int total FROM users WHERE clinic_id=$1 AND active=true',[clinicId]),client.query('SELECT COUNT(*)::int total FROM units WHERE clinic_id=$1 AND active=true',[clinicId]),client.query("SELECT COUNT(*)::int total FROM patients WHERE clinic_id=$1 AND status!='archived'",[clinicId])])).map(result=>result.rows[0].total),limits=target.limits_json||{},usage={users:counts[0],units:counts[1],patients:counts[2]},exceeded=Object.keys(usage).filter(key=>limits[key]!=null&&usage[key]>Number(limits[key]));if(exceeded.length)throw Object.assign(new Error(`O uso atual excede o limite do plano para: ${exceeded.join(', ')}`),{status:409});}const{rows}=await client.query(`INSERT INTO subscription_change_requests(id,clinic_id,requested_by,request_type,from_plan_key,to_plan_key,billing_cycle,reason,effective_at,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending',$10,$10) RETURNING id,request_type,from_plan_key,to_plan_key,billing_cycle,reason,effective_at,status,created_at`,[request.id,clinicId,userId,request.type,current.plan_key,request.planKey||null,request.billingCycle||null,request.reason||null,current.current_period_ends_at,request.createdAt]);return rows[0];});},
    async activeLegalDocuments(){const{rows}=await pool.query(`SELECT DISTINCT ON(key) key,version,title,content_url,effective_at FROM legal_documents WHERE active=true ORDER BY key,effective_at DESC`);return rows;},
    async createSignup(request){const client=await pool.connect();try{await client.query('BEGIN');const plan=(await client.query('SELECT key FROM plans WHERE key=$1 AND active=true AND monthly_price_cents IS NOT NULL',[request.planKey])).rows[0];if(!plan)throw Object.assign(new Error('Plano comercial indisponível'),{status:400});if((await client.query('SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1',[request.email])).rows[0])throw Object.assign(new Error('Já existe uma conta com este e-mail'),{status:409});await client.query("UPDATE signup_requests SET status='expired',updated_at=$2 WHERE lower(email)=lower($1) AND status='pending_email' AND expires_at<=$2",[request.email,request.createdAt]);const pending=(await client.query("SELECT id FROM signup_requests WHERE lower(email)=lower($1) AND status='pending_email' LIMIT 1",[request.email])).rows[0];if(pending)throw Object.assign(new Error('Já existe um cadastro aguardando verificação para este e-mail'),{status:409});const{rows}=await client.query(`INSERT INTO signup_requests(id,email,professional_name,clinic_name,clinic_document,phone,plan_key,billing_cycle,password_hash,verification_token_hash,terms_version,privacy_version,expires_at,created_ip,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15) RETURNING id,email,status,expires_at`,[request.id,request.email,request.professionalName,request.clinicName,request.clinicDocument,request.phone,request.planKey,request.billingCycle,request.passwordHash,request.tokenHash,request.termsVersion,request.privacyVersion,request.expiresAt,request.ip,request.createdAt]);await client.query('COMMIT');return rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
    async cancelSignup(id,at){await pool.query("UPDATE signup_requests SET status='cancelled',updated_at=$2 WHERE id=$1 AND status='pending_email'",[id,at]);},
    async verifySignup(tokenHash,{clinicId,userId,unitId,acceptanceIds,verifiedAt,trialEndsAt,ip,userAgent}){const client=await pool.connect();try{await client.query('BEGIN');const request=(await client.query("SELECT * FROM signup_requests WHERE verification_token_hash=$1 AND status='pending_email' AND expires_at>$2 FOR UPDATE",[tokenHash,verifiedAt])).rows[0];if(!request)throw Object.assign(new Error('Link de verificação inválido ou expirado'),{status:400});if((await client.query('SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1',[request.email])).rows[0])throw Object.assign(new Error('Já existe uma conta com este e-mail'),{status:409});await client.query("SELECT set_config('app.clinic_id',$1,true)",[clinicId]);await client.query('INSERT INTO clinics(id,name,created_at) VALUES($1,$2,$3)',[clinicId,request.clinic_name,verifiedAt]);await client.query(`INSERT INTO clinic_subscriptions(clinic_id,plan_key,status,trial_ends_at,current_period_ends_at,created_at,updated_at,billing_cycle) VALUES($1,$2,'trialing',$3,$3,$4,$4,$5)`,[clinicId,request.plan_key,trialEndsAt,verifiedAt,request.billing_cycle]);await client.query('INSERT INTO units(id,clinic_id,name,address,rooms,active,created_at) VALUES($1,$2,$3,NULL,1,true,$4)',[unitId,clinicId,'Unidade principal',verifiedAt]);await client.query(`INSERT INTO users(id,clinic_id,unit_id,name,email,password_hash,role,active,created_at) VALUES($1,$2,$3,$4,$5,$6,'admin',true,$7)`,[userId,clinicId,unitId,request.professional_name,request.email,request.password_hash,verifiedAt]);await client.query(`INSERT INTO legal_acceptances(id,clinic_id,user_id,document_key,document_version,accepted_at,ip,user_agent) VALUES($1,$2,$3,'terms_of_use',$4,$5,$6,$7),($8,$2,$3,'privacy_policy',$9,$5,$6,$7)`,[acceptanceIds[0],clinicId,userId,request.terms_version,verifiedAt,ip,userAgent,acceptanceIds[1],request.privacy_version]);await client.query("UPDATE signup_requests SET status='verified',verified_at=$2,updated_at=$2 WHERE id=$1",[request.id,verifiedAt]);await client.query('COMMIT');return{clinic_id:clinicId,user_id:userId,email:request.email,plan_key:request.plan_key,status:'trialing',trial_ends_at:trialEndsAt};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
    async configureModule(clinicId,userId,moduleKey,enabled,reason){const result=await withTenant(pool,clinicId,async client=>{const{rows}=await client.query('SELECT p.modules_json FROM clinic_subscriptions cs JOIN plans p ON p.key=cs.plan_key WHERE cs.clinic_id=$1',[clinicId]);if(enabled&&!rows[0]?.modules_json?.includes(moduleKey))return{upgradeRequired:true};await client.query(`INSERT INTO clinic_module_overrides(clinic_id,module_key,enabled,reason,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,now()) ON CONFLICT(clinic_id,module_key) DO UPDATE SET enabled=excluded.enabled,reason=excluded.reason,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,[clinicId,moduleKey,enabled,reason,userId]);return{upgradeRequired:false};});return{...result,context:result.upgradeRequired?null:await this.context(clinicId)};},
    close(){return pool.end();}
  };
}
