import { postgresPool, withTenant } from './db/postgres.js';
import { moduleCatalog } from './modules.js';

export function postgresAuthStore(pool=postgresPool()){
  return{
    kind:'postgres',
    async health(){const{rows}=await pool.query('SELECT 1 AS connected');return rows[0]?.connected===1;},
    async findUser(email){const{rows}=await pool.query('SELECT * FROM psyche_login_identity($1)',[email]);return rows[0]||null;},
    async userByToken(tokenHash,now){const{rows}=await pool.query('SELECT * FROM psyche_session_identity($1,$2)',[tokenHash,now]);return rows[0]||null;},
    async sessionTimeout(clinicId){return withTenant(pool,clinicId,async client=>{const{rows}=await client.query("SELECT value_json FROM clinic_settings WHERE clinic_id=$1 AND key='security'",[clinicId]);return Number(rows[0]?.value_json?.session_timeout_minutes)||480;});},
    async createSession({id,userId,clinicId,tokenHash,expiresAt,createdAt}){return withTenant(pool,clinicId,client=>client.query('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES ($1,$2,$3,$4,$5)',[id,userId,tokenHash,expiresAt,createdAt]));},
    async deleteExpired(clinicId,now){return withTenant(pool,clinicId,client=>client.query('DELETE FROM sessions WHERE expires_at<=$1',[now]));},
    async deleteSession(tokenHash,clinicId){if(!clinicId)return;return withTenant(pool,clinicId,client=>client.query('DELETE FROM sessions WHERE token_hash=$1',[tokenHash]));},
    async context(clinicId){return withTenant(pool,clinicId,async client=>{const{rows}=await client.query(`SELECT c.id,c.name,c.created_at,cs.plan_key,cs.status,cs.trial_ends_at,cs.current_period_ends_at,p.name plan_name,p.modules_json,p.limits_json FROM clinics c JOIN clinic_subscriptions cs ON cs.clinic_id=c.id JOIN plans p ON p.key=cs.plan_key WHERE c.id=$1`,[clinicId]);const row=rows[0];if(!row)return null;const enabled=new Set(row.modules_json||[]),overrides=(await client.query('SELECT module_key,enabled FROM clinic_module_overrides WHERE clinic_id=$1',[clinicId])).rows;overrides.forEach(item=>item.enabled?enabled.add(item.module_key):enabled.delete(item.module_key));const counts=await Promise.all([client.query('SELECT COUNT(*)::int total FROM users WHERE clinic_id=$1 AND active=true',[clinicId]),client.query('SELECT COUNT(*)::int total FROM units WHERE clinic_id=$1 AND active=true',[clinicId]),client.query("SELECT COUNT(*)::int total FROM patients WHERE clinic_id=$1 AND status!='archived'",[clinicId])]);return{tenant:{id:row.id,name:row.name,created_at:row.created_at},subscription:{plan_key:row.plan_key,plan_name:row.plan_name,status:row.status,trial_ends_at:row.trial_ends_at,current_period_ends_at:row.current_period_ends_at},modules:Object.fromEntries(Object.entries(moduleCatalog).map(([key,value])=>[key,{...value,enabled:enabled.has(key)}])),limits:row.limits_json||{},usage:{users:counts[0].rows[0].total,units:counts[1].rows[0].total,patients:counts[2].rows[0].total}};});},
    async configureModule(clinicId,userId,moduleKey,enabled,reason){const result=await withTenant(pool,clinicId,async client=>{const{rows}=await client.query('SELECT p.modules_json FROM clinic_subscriptions cs JOIN plans p ON p.key=cs.plan_key WHERE cs.clinic_id=$1',[clinicId]);if(enabled&&!rows[0]?.modules_json?.includes(moduleKey))return{upgradeRequired:true};await client.query(`INSERT INTO clinic_module_overrides(clinic_id,module_key,enabled,reason,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,now()) ON CONFLICT(clinic_id,module_key) DO UPDATE SET enabled=excluded.enabled,reason=excluded.reason,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,[clinicId,moduleKey,enabled,reason,userId]);return{upgradeRequired:false};});return{...result,context:result.upgradeRequired?null:await this.context(clinicId)};},
    close(){return pool.end();}
  };
}
