import { postgresPool, withTenant } from './db/postgres.js';

export function postgresFinanceStore(pool=postgresPool()){
  return{
    kind:'postgres',
    async summary(clinicId,month){return withTenant(pool,clinicId,async client=>{const{rows}=await client.query(`SELECT type,status,COALESCE(SUM(amount_cents),0)::bigint total,COUNT(*)::int count FROM financial_entries WHERE clinic_id=$1 AND to_char(COALESCE(due_date,created_at::date),'YYYY-MM')=$2 AND status!='void' GROUP BY type,status`,[clinicId,month]);const sum=(type,statuses)=>rows.filter(row=>row.type===type&&statuses.includes(row.status)).reduce((total,row)=>total+Number(row.total),0),received=sum('income',['paid']),receivable=sum('income',['pending','overdue']),expenses=sum('expense',['paid','pending','overdue']),overdue=sum('income',['overdue']);return{month,received_cents:received,receivable_cents:receivable,expenses_cents:expenses,overdue_cents:overdue,balance_cents:received-expenses,entries:rows.reduce((total,row)=>total+Number(row.count),0)};});},
    async list(clinicId,filters={}){return withTenant(pool,clinicId,async client=>{const conditions=['f.clinic_id=$1'],values=[clinicId];for(const[key,column]of[['type','f.type'],['status','f.status']])if(filters[key]){values.push(filters[key]);conditions.push(`${column}=$${values.length}`);}if(filters.from){values.push(filters.from);conditions.push(`COALESCE(f.due_date,f.created_at::date)>=$${values.length}`);}if(filters.to){values.push(filters.to);conditions.push(`COALESCE(f.due_date,f.created_at::date)<=$${values.length}`);}if(filters.q){values.push(`%${filters.q.slice(0,80)}%`);conditions.push(`(f.description ILIKE $${values.length} OR p.name ILIKE $${values.length})`);}return(await client.query(`SELECT f.*,p.name patient_name FROM financial_entries f LEFT JOIN patients p ON p.id=f.patient_id WHERE ${conditions.join(' AND ')} ORDER BY COALESCE(f.due_date,f.created_at::date) DESC LIMIT 500`,values)).rows;});},
    async create(clinicId,entry){return withTenant(pool,clinicId,async client=>{if(entry.patientId&&!((await client.query('SELECT id FROM patients WHERE id=$1 AND clinic_id=$2',[entry.patientId,clinicId])).rows[0]))throw Object.assign(new Error('Paciente inválido'),{status:400});return(await client.query(`INSERT INTO financial_entries(id,clinic_id,patient_id,appointment_id,description,type,amount_cents,due_date,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[entry.id,clinicId,entry.patientId,entry.appointmentId,entry.description,entry.type,entry.amountCents,entry.dueDate,entry.status,entry.createdAt])).rows[0];});},
    async get(clinicId,id){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM financial_entries WHERE id=$1 AND clinic_id=$2',[id,clinicId])).rows[0]||null);},
    async update(clinicId,id,entry){return withTenant(pool,clinicId,async client=>(await client.query(`UPDATE financial_entries SET description=$3,type=$4,amount_cents=$5,due_date=$6,status=$7 WHERE id=$1 AND clinic_id=$2 RETURNING *`,[id,clinicId,entry.description,entry.type,entry.amountCents,entry.dueDate,entry.status])).rows[0]||null);},
    async remove(clinicId,id){return withTenant(pool,clinicId,client=>client.query('DELETE FROM financial_entries WHERE id=$1 AND clinic_id=$2',[id,clinicId]));},
    close(){return pool.end();}
  };
}
