import { postgresPool, withTenant } from './db/postgres.js';

export function postgresPayablesStore(pool=postgresPool()){
  return{
    kind:'postgres',
    async suppliers(clinicId){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM suppliers WHERE clinic_id=$1 ORDER BY active DESC,name',[clinicId])).rows);},
    async createSupplier(clinicId,supplier){return withTenant(pool,clinicId,async client=>(await client.query(`INSERT INTO suppliers(id,clinic_id,name,document,email,phone,active,created_at) VALUES($1,$2,$3,$4,$5,$6,true,$7) RETURNING *`,[supplier.id,clinicId,supplier.name,supplier.document,supplier.email,supplier.phone,supplier.createdAt])).rows[0]);},
    async summary(clinicId,month){return withTenant(pool,clinicId,async client=>{const row=(await client.query(`SELECT COALESCE(SUM(amount_cents) FILTER(WHERE status='paid'),0)::bigint paid,COALESCE(SUM(amount_cents) FILTER(WHERE status='pending'),0)::bigint pending,COALESCE(SUM(amount_cents) FILTER(WHERE status='pending' AND due_date<CURRENT_DATE),0)::bigint overdue,COUNT(*) FILTER(WHERE status='pending' AND due_date<CURRENT_DATE)::int overdue_count,COUNT(*)::int total FROM accounts_payable WHERE clinic_id=$1 AND to_char(due_date,'YYYY-MM')=$2 AND status!='cancelled'`,[clinicId,month])).rows[0];return{month,paid_cents:Number(row.paid),pending_cents:Number(row.pending),overdue_cents:Number(row.overdue),overdue_count:Number(row.overdue_count),total:Number(row.total)};});},
    async list(clinicId,filters={}){return withTenant(pool,clinicId,async client=>{const conditions=['a.clinic_id=$1'],values=[clinicId];if(filters.from){values.push(filters.from);conditions.push(`a.due_date>=$${values.length}`);}if(filters.to){values.push(filters.to);conditions.push(`a.due_date<=$${values.length}`);}if(filters.status==='overdue')conditions.push("a.status='pending' AND a.due_date<CURRENT_DATE");else if(filters.status){values.push(filters.status);conditions.push(`a.status=$${values.length}`);}if(filters.supplierId){values.push(filters.supplierId);conditions.push(`a.supplier_id=$${values.length}`);}if(filters.q){values.push(`%${filters.q.slice(0,80)}%`);conditions.push(`(a.description ILIKE $${values.length} OR s.name ILIKE $${values.length})`);}return(await client.query(`SELECT a.*,s.name supplier_name,u.name unit_name,CASE WHEN a.status='pending' AND a.due_date<CURRENT_DATE THEN 'overdue' ELSE a.status END effective_status FROM accounts_payable a LEFT JOIN suppliers s ON s.id=a.supplier_id LEFT JOIN units u ON u.id=a.unit_id WHERE ${conditions.join(' AND ')} ORDER BY a.due_date,a.created_at LIMIT 500`,values)).rows;});},
    async create(clinicId,items){return withTenant(pool,clinicId,async client=>{const supplierIds=[...new Set(items.map(item=>item.supplierId).filter(Boolean))],unitIds=[...new Set(items.map(item=>item.unitId).filter(Boolean))];if(supplierIds.length){const total=Number((await client.query('SELECT COUNT(*) total FROM suppliers WHERE clinic_id=$1 AND id=ANY($2::text[])',[clinicId,supplierIds])).rows[0].total);if(total!==supplierIds.length)throw Object.assign(new Error('Fornecedor inválido'),{status:400});}if(unitIds.length){const total=Number((await client.query('SELECT COUNT(*) total FROM units WHERE clinic_id=$1 AND id=ANY($2::text[])',[clinicId,unitIds])).rows[0].total);if(total!==unitIds.length)throw Object.assign(new Error('Unidade inválida'),{status:400});}const rows=[];for(const item of items)rows.push((await client.query(`INSERT INTO accounts_payable(id,clinic_id,supplier_id,unit_id,financial_entry_id,description,category,amount_cents,due_date,paid_at,status,installment_number,installments_total,recurrence,notes,created_at,updated_at) VALUES($1,$2,$3,$4,NULL,$5,$6,$7,$8,NULL,'pending',$9,$10,$11,$12,$13,$13) RETURNING *`,[item.id,clinicId,item.supplierId,item.unitId,item.description,item.category,item.amountCents,item.dueDate,item.installmentNumber,item.installmentsTotal,item.recurrence,item.notes,item.createdAt])).rows[0]);return rows;});},
    async get(clinicId,id){return withTenant(pool,clinicId,async client=>(await client.query('SELECT * FROM accounts_payable WHERE id=$1 AND clinic_id=$2',[id,clinicId])).rows[0]||null);},
    async edit(clinicId,id,item){return withTenant(pool,clinicId,async client=>(await client.query(`UPDATE accounts_payable SET supplier_id=$3,unit_id=$4,description=$5,category=$6,amount_cents=$7,due_date=$8,notes=$9,updated_at=$10 WHERE id=$1 AND clinic_id=$2 AND status='pending' RETURNING *`,[id,clinicId,item.supplierId,item.unitId,item.description,item.category,item.amountCents,item.dueDate,item.notes,item.updatedAt])).rows[0]||null);},
    async pay(clinicId,id,{financialId,paidAt,createdAt}){return withTenant(pool,clinicId,async client=>{const current=(await client.query('SELECT * FROM accounts_payable WHERE id=$1 AND clinic_id=$2 FOR UPDATE',[id,clinicId])).rows[0];if(!current)return null;if(current.status==='paid')throw Object.assign(new Error('Conta já está paga'),{status:409});await client.query(`INSERT INTO financial_entries(id,clinic_id,patient_id,appointment_id,description,type,amount_cents,due_date,status,created_at) VALUES($1,$2,NULL,NULL,$3,'expense',$4,$5,'paid',$6)`,[financialId,clinicId,`Conta paga · ${current.description}`,current.amount_cents,current.due_date,createdAt]);return(await client.query("UPDATE accounts_payable SET status='paid',paid_at=$3,financial_entry_id=$4,updated_at=$5 WHERE id=$1 AND clinic_id=$2 RETURNING *",[id,clinicId,paidAt,financialId,createdAt])).rows[0];});},
    async cancel(clinicId,id,updatedAt){return withTenant(pool,clinicId,async client=>{const current=(await client.query('SELECT * FROM accounts_payable WHERE id=$1 AND clinic_id=$2 FOR UPDATE',[id,clinicId])).rows[0];if(!current)return null;if(current.financial_entry_id)await client.query("UPDATE financial_entries SET status='void' WHERE id=$1 AND clinic_id=$2",[current.financial_entry_id,clinicId]);return(await client.query("UPDATE accounts_payable SET status='cancelled',updated_at=$3 WHERE id=$1 AND clinic_id=$2 RETURNING *",[id,clinicId,updatedAt])).rows[0];});},
    close(){return pool.end();}
  };
}
