const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=name=>String(name||'').split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'—';
const time=value=>{if(!value)return'Nova';const date=new Date(value),today=new Date();return date.toDateString()===today.toDateString()?date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});};

export function initChat({api,showToast,navigate}){
  let conversations=[],active=null,patients=[],searchTimer;
  const list=document.querySelector('#conversationItems'),messages=document.querySelector('#chatMessages'),form=document.querySelector('#messageForm'),input=form.querySelector('textarea');
  document.body.insertAdjacentHTML('beforeend','<dialog class="crud-dialog new-conversation-dialog" id="newConversationDialog"><div class="modal-head"><div><div class="eyebrow">COMUNICAÇÃO SEGURA</div><h2>Nova conversa</h2></div><button class="close" data-close-conversation>×</button></div><form id="newConversationForm"><div class="field"><label>Paciente</label><select name="patient_id" required></select></div><p class="utility-copy">Será aberto o canal protegido já existente ou criada uma nova conversa para o paciente.</p><div class="modal-actions"><button type="button" class="secondary-btn" data-close-conversation>Cancelar</button><button class="primary-btn">Abrir conversa</button></div></form></dialog>');
  const newDialog=document.querySelector('#newConversationDialog');
  const setComposer=enabled=>{input.disabled=!enabled;form.querySelector('button').disabled=!enabled;};
  const renderList=()=>{if(!conversations.length){list.innerHTML='<div class="conversation-empty"><span>◌</span><strong>Nenhuma conversa</strong><small>Inicie um canal seguro com um paciente.</small></div>';return;}list.innerHTML=conversations.map(c=>`<button class="conversation ${active?.id===c.id?'active':''}" data-conversation="${c.id}"><div class="mini-avatar">${initials(c.patient_name)}</div><div><strong>${esc(c.patient_name)}</strong><span>${esc(c.last_message||'Canal seguro iniciado')}</span></div><div class="conversation-meta"><time>${time(c.last_message_at)}</time>${Number(c.unread_count)?`<b>${c.unread_count}</b>`:''}</div></button>`).join('');};
  const renderMessages=data=>{messages.innerHTML=data.length?data.map(m=>`<div class="message-group ${m.sender_type==='staff'?'sent':'received'}"><div class="bubble ${m.sender_type==='staff'?'sent':'received'}">${esc(m.body)}</div><time>${time(m.created_at)}${m.sender_type==='staff'?' · Enviada':m.read_at?' · Lida':''}</time></div>`).join(''):'<div class="chat-empty"><span>✦</span><strong>Comece esta conversa</strong><small>As mensagens são criptografadas antes de serem armazenadas.</small></div>';messages.scrollTop=messages.scrollHeight;};
  const loadSummary=async()=>{const{data}=await api.conversationSummary();document.querySelector('#conversationTotal').textContent=data.conversations;document.querySelector('#conversationUnread').textContent=data.unread;document.querySelector('#messagesToday').textContent=data.messages_today;const badge=document.querySelector('[data-view="chat"] .nav-badge');if(data.unread){badge.textContent=data.unread;badge.hidden=false;}else badge.hidden=true;};
  const open=async conversation=>{if(!conversation)return;active=conversation;renderList();document.querySelector('#chatAvatar').textContent=initials(conversation.patient_name);document.querySelector('#chatName').textContent=conversation.patient_name;document.querySelector('#chatStatus').textContent='Paciente · canal seguro e auditado';document.querySelector('#chatPatientProfile').disabled=false;setComposer(true);messages.innerHTML='<div class="dashboard-loading">Carregando histórico...</div>';document.querySelector('#conversationList').classList.remove('mobile-open');try{const result=await api.messages(conversation.id);renderMessages(result.data);await api.markConversationRead(conversation.id);conversation.unread_count=0;renderList();await loadSummary();}catch(err){messages.innerHTML=`<div class="dashboard-error">${esc(err.message)}</div>`;}};
  const load=async({preserve=true}={})=>{if(!api.token)return;try{const query=document.querySelector('#conversationSearch').value.trim(),result=await api.conversations({q:query});conversations=result.data;const current=preserve&&active?conversations.find(x=>x.id===active.id):null;active=current||null;renderList();await loadSummary();if(current)await open(current);}catch(err){list.innerHTML=`<div class="dashboard-error">${esc(err.message)}</div>`;}};
  form.addEventListener('submit',async e=>{e.preventDefault();const body=input.value.trim();if(!active||!body)return;const button=form.querySelector('button');button.disabled=true;try{await api.sendMessage(active.id,body);input.value='';input.dispatchEvent(new Event('input'));const result=await api.messages(active.id);renderMessages(result.data);await load();showToast('Mensagem cifrada e enviada');}catch(err){showToast(err.message);}finally{button.disabled=false;input.focus();}});
  input.addEventListener('input',()=>{document.querySelector('#messageCount').textContent=`${input.value.length}/5000`;input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,110)}px`;});
  list.addEventListener('click',e=>{const button=e.target.closest('[data-conversation]');if(button)open(conversations.find(x=>x.id===button.dataset.conversation));});
  document.querySelector('#conversationSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>load({preserve:false}),250);});
  document.querySelectorAll('[data-quick]').forEach(button=>button.addEventListener('click',()=>{if(!active){showToast('Selecione uma conversa');return;}input.value=button.dataset.quick;input.dispatchEvent(new Event('input'));input.focus();}));
  document.querySelector('.chat-action').addEventListener('click',()=>{const select=newDialog.querySelector('select');select.innerHTML=patients.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(!patients.length){showToast('Cadastre um paciente primeiro');return;}newDialog.showModal();});
  newDialog.querySelectorAll('[data-close-conversation]').forEach(x=>x.addEventListener('click',()=>newDialog.close()));newDialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();try{const patientId=new FormData(e.target).get('patient_id'),result=await api.createConversation(patientId);newDialog.close();await load({preserve:false});const conversation=conversations.find(x=>x.id===result.data.id)||conversations.find(x=>x.patient_id===patientId);await open(conversation);showToast('Canal seguro aberto');}catch(err){showToast(err.message);}});
  document.querySelector('#chatPatientProfile').addEventListener('click',()=>{navigate('patients');const search=document.querySelector('#patientSearch');search.value=active?.patient_name||'';search.dispatchEvent(new Event('input'));});
  document.querySelector('#mobileOpenConversations').addEventListener('click',()=>document.querySelector('#conversationList').classList.add('mobile-open'));document.querySelector('#mobileCloseConversations').addEventListener('click',()=>document.querySelector('#conversationList').classList.remove('mobile-open'));
  window.addEventListener('psyche:hydrated',e=>{patients=e.detail.patients||[];load({preserve:false});});window.addEventListener('psyche:refresh',()=>load());
  return{load,open};
}
