const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const labels={anamnesis:'Anamnese',case_plan:'Planejamento de caso',evolution:'Evolução',referral:'Encaminhamento',closure:'Encerramento'};
const schemas={
  anamnesis:[['demand','Demanda e motivo da procura'],['history','História da demanda'],['personal_history','História pessoal e desenvolvimento'],['family_context','Contexto familiar e vínculos'],['health','Saúde, tratamentos e medicações'],['routine','Rotina, sono, alimentação e trabalho'],['support_network','Rede de apoio e recursos'],['risk_assessment','Avaliação de riscos e fatores de proteção'],['expectations','Expectativas e objetivos iniciais']],
  case_plan:[['formulation','Formulação compreensiva do caso'],['objectives','Objetivos acordados'],['interventions','Estratégias e intervenções planejadas'],['frequency','Frequência e modalidade'],['indicators','Indicadores de acompanhamento'],['risk_plan','Plano de manejo de riscos'],['review_criteria','Critérios e data de revisão']],
  evolution:[['summary','Síntese do atendimento'],['procedures','Procedimentos e intervenções'],['response','Respostas observadas'],['progress','Evolução em relação aos objetivos'],['referrals','Encaminhamentos e decisões'],['next_steps','Próximos passos']],
  referral:[['reason','Motivo do encaminhamento'],['destination','Profissional ou serviço de destino'],['essential_information','Informações estritamente necessárias'],['continuity','Plano de continuidade do cuidado']],
  closure:[['reason','Motivo do encerramento'],['process_summary','Síntese do processo'],['outcomes','Resultados e objetivos alcançados'],['guidance','Orientações e encaminhamentos finais']]
};

export function initClinicalRecords({api,showToast}){
  let patient=null,type='anamnesis',records=[],profile=null,policy=null;
  document.body.insertAdjacentHTML('beforeend',`<dialog class="clinical-record-dialog" id="clinicalRecordDialog"><div class="clinical-record-head"><div><div class="eyebrow">PRONTUÁRIO PSICOLÓGICO</div><h2 id="clinicalPatientName">Paciente</h2><p>Registro longitudinal, sigiloso e versionado</p></div><button class="close" id="closeClinicalRecord" aria-label="Fechar">×</button></div><div class="clinical-billing-status" id="clinicalBillingStatus"></div><nav class="clinical-record-tabs" id="clinicalRecordTabs">${Object.entries(labels).map(([key,label])=>`<button data-record-type="${key}" class="${key==='anamnesis'?'active':''}">${label}</button>`).join('')}</nav><div class="clinical-record-toolbar"><div><strong id="clinicalRecordTitle">Anamnese</strong><span>Registros anteriores permanecem preservados para auditoria.</span></div><button class="primary-btn" id="newClinicalRecord">＋ Novo registro</button></div><div class="clinical-record-list" id="clinicalRecordList"></div></dialog><dialog class="crud-dialog clinical-editor" id="clinicalRecordEditor"><div class="modal-head"><div><div class="eyebrow">REGISTRO CLÍNICO</div><h2 id="clinicalEditorTitle"></h2></div><button class="close" data-close-clinical-editor>×</button></div><form id="clinicalRecordForm"><div class="field full"><label>Título</label><input name="title" required maxlength="180"></div><div id="clinicalRecordFields" class="clinical-record-fields"></div><div class="clinical-record-options"><label>Compartilhamento<select name="visibility"><option value="record">Prontuário acessível à pessoa atendida</option><option value="restricted">Registro exclusivo do profissional</option></select></label><label>Estado<select name="status"><option value="active">Ativo/concluído</option><option value="draft">Rascunho</option></select></label></div><div class="clinical-ethics-note">Registre apenas informações necessárias, pertinentes e tecnicamente fundamentadas. Protocolos de testes e materiais privativos não pertencem ao prontuário compartilhável.</div><div class="modal-actions"><button type="button" class="secondary-btn" data-close-clinical-editor>Cancelar</button><button class="primary-btn">Salvar nova versão</button></div></form></dialog>`);
  const dialog=document.querySelector('#clinicalRecordDialog'),editor=document.querySelector('#clinicalRecordEditor'),list=document.querySelector('#clinicalRecordList');
  const billingText=()=>{if(!profile||!policy)return'';const pending=profile.finance?.pending_cents||0,timing={before_booking:'Cobrança prevista antes do agendamento',before_session:'Cobrança prevista antes da sessão',after_session:'Cobrança prevista após a sessão'}[policy.timing];return `<div><strong>${pending?`${money(pending)} pendentes`:'Sem pendências financeiras'}</strong><span>${timing} · tolerância de ${policy.grace_days} dias</span></div><span class="tag ${pending?'orange':''}">${pending?'Acompanhamento financeiro':'Regular'}</span><small>Questões financeiras geram aviso ou revisão administrativa; não bloqueiam automaticamente cuidado urgente ou emergencial.</small>`;};
  const render=()=>{document.querySelector('#clinicalRecordTitle').textContent=labels[type];document.querySelectorAll('[data-record-type]').forEach(button=>button.classList.toggle('active',button.dataset.recordType===type));list.innerHTML=records.length?records.map(record=>`<article class="clinical-record-card"><header><div><span>${labels[record.type]} · versão ${record.version}</span><h3>${esc(record.title)}</h3></div><div><span class="tag ${record.visibility==='restricted'?'orange':''}">${record.visibility==='restricted'?'Exclusivo':'Prontuário'}</span><span class="tag ${record.status==='draft'?'gray':''}">${record.status==='draft'?'Rascunho':'Ativo'}</span></div></header><div class="clinical-record-content">${Object.entries(record.content||{}).filter(([,value])=>value).map(([key,value])=>`<section><strong>${esc(schemas[record.type]?.find(([field])=>field===key)?.[1]||key)}</strong><p>${esc(value)}</p></section>`).join('')}</div><footer>${new Date(record.occurred_at).toLocaleString('pt-BR')} · ${esc(record.professional_name||'Profissional responsável')}</footer></article>`).join(''):`<div class="agenda-empty clinical-empty"><span>✦</span><strong>Nenhum registro de ${labels[type].toLowerCase()}</strong><small>Crie o primeiro registro para iniciar o acompanhamento longitudinal.</small></div>`;};
  const load=async()=>{if(!patient)return;list.innerHTML='<div class="dashboard-loading">Carregando prontuário cifrado...</div>';try{const[result,patientResult,policyResult]=await Promise.all([api.clinicalRecords(patient.id,type),api.patient(patient.id),api.billingPolicy()]);records=result.data;profile=patientResult.data;policy=policyResult.data;document.querySelector('#clinicalBillingStatus').innerHTML=billingText();render();}catch(error){list.innerHTML=`<div class="dashboard-error">${esc(error.message)}</div>`;}};
  const open=current=>{patient=current;document.querySelector('#clinicalPatientName').textContent=current.name;dialog.showModal();load();};
  const openEditor=()=>{document.querySelector('#clinicalEditorTitle').textContent=`Novo registro · ${labels[type]}`;const form=document.querySelector('#clinicalRecordForm');form.reset();form.elements.title.value=`${labels[type]} · ${new Date().toLocaleDateString('pt-BR')}`;document.querySelector('#clinicalRecordFields').innerHTML=schemas[type].map(([key,label])=>`<div class="field full"><label>${label}</label><textarea name="${key}" rows="3" maxlength="8000"></textarea></div>`).join('');editor.showModal();};
  const ensureProfileAction=()=>{const actions=document.querySelector('#patientProfile .profile-actions');if(actions&&!actions.querySelector('#openClinicalRecord'))actions.insertAdjacentHTML('afterbegin','<button class="secondary-btn" id="openClinicalRecord">Prontuário</button>');};
  document.addEventListener('click',event=>{const row=event.target.closest('[data-patient-id]');if(row){patient={id:row.dataset.patientId,name:row.querySelector('strong')?.textContent||'Paciente'};setTimeout(ensureProfileAction,0);setTimeout(ensureProfileAction,120);}if(event.target.closest('#openClinicalRecord')&&patient)open(patient);},true);
  const observer=new MutationObserver(ensureProfileAction);observer.observe(document.querySelector('#patientProfile'),{subtree:true,childList:true});
  document.querySelector('#closeClinicalRecord').addEventListener('click',()=>dialog.close());document.querySelector('#newClinicalRecord').addEventListener('click',openEditor);document.querySelectorAll('[data-close-clinical-editor]').forEach(button=>button.addEventListener('click',()=>editor.close()));
  document.querySelector('#clinicalRecordTabs').addEventListener('click',event=>{const button=event.target.closest('[data-record-type]');if(!button)return;type=button.dataset.recordType;load();});
  document.querySelector('#clinicalRecordForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),content=Object.fromEntries(schemas[type].map(([key])=>[key,data[key]?.trim()||'']).filter(([,value])=>value));if(!Object.keys(content).length){showToast('Preencha ao menos um campo clínico');return;}const submit=form.querySelector('button[type="submit"],button:not([type])');submit.disabled=true;try{await api.createClinicalRecord(patient.id,{type,title:data.title,content,visibility:data.visibility,status:data.status,occurred_at:new Date().toISOString()});editor.close();showToast('Nova versão registrada e cifrada');await load();}catch(error){showToast(error.message);}finally{submit.disabled=false;}});
  return{open,load};
}
