const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const labels={paid:'Pago',pending:'Pendente',overdue:'Em atraso',void:'Estornado'};
const todayMonth=()=>new Date().toISOString().slice(0,7);
const monthRange=month=>{const [year,index]=month.split('-').map(Number),last=new Date(year,index,0).getDate();return{from:`${month}-01`,to:`${month}-${String(last).padStart(2,'0')}`};};

export function initFinance({api,showToast}){
  let items=[],loading=false,searchTimer;
  const month=document.querySelector('#financeMonth'),rows=document.querySelector('#financeRows');
  month.value=todayMonth();
  document.body.insertAdjacentHTML('beforeend','<dialog class="crud-dialog finance-detail-dialog" id="financeDetail"><div id="financeDetailContent"></div></dialog>');
  const dialog=document.querySelector('#financeDetail');
  const filters=()=>({...monthRange(month.value||todayMonth()),q:document.querySelector('#financeSearch').value.trim(),type:document.querySelector('#financeType').value,status:document.querySelector('#financeStatus').value});
  const renderSummary=data=>{document.querySelector('#financeReceived').textContent=money(data.received_cents);document.querySelector('#financeReceivable').textContent=money(data.receivable_cents);document.querySelector('#financeExpenses').textContent=money(data.expenses_cents);const balance=document.querySelector('#financeBalance');balance.textContent=money(data.balance_cents);balance.classList.toggle('negative',data.balance_cents<0);document.querySelector('#financeOverdue').textContent=money(data.overdue_cents);};
  const render=()=>{document.querySelector('#financeResultCount').textContent=`${items.length} ${items.length===1?'lançamento':'lançamentos'}`;if(!items.length){rows.innerHTML='<tr><td colspan="7"><div class="agenda-empty finance-empty"><span>↕</span><strong>Nenhum lançamento encontrado</strong><small>Ajuste os filtros ou registre uma receita ou despesa.</small></div></td></tr>';return;}rows.innerHTML=items.map(x=>`<tr class="finance-row" tabindex="0" data-finance-id="${x.id}"><td>${new Date(`${x.due_date||x.created_at.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')}</td><td><strong>${esc(x.description)}</strong></td><td>${esc(x.patient_name||'—')}</td><td><span class="tag ${x.type==='expense'?'orange':''}">${x.type==='income'?'Receita':'Despesa'}</span></td><td><strong class="finance-amount ${x.type}">${x.type==='expense'?'− ':'+ '}${money(x.amount_cents)}</strong></td><td><span class="finance-status status-${x.status}">${labels[x.status]||esc(x.status)}</span></td><td><button class="row-action" aria-label="Abrir lançamento">›</button></td></tr>`).join('');};
  const load=async()=>{if(!api.token||loading)return;loading=true;rows.innerHTML='<tr><td colspan="7"><div class="dashboard-loading">Carregando lançamentos...</div></td></tr>';try{const [list,summary]=await Promise.all([api.finance(filters()),api.financeSummary(month.value)]);items=list.data;render();renderSummary(summary.data);}catch(err){rows.innerHTML=`<tr><td colspan="7"><div class="dashboard-error">${esc(err.message)}</div></td></tr>`;}finally{loading=false;}};
  const open=item=>{dialog.querySelector('#financeDetailContent').innerHTML=`<div class="modal-head"><div><div class="eyebrow">LANÇAMENTO FINANCEIRO</div><h2>${esc(item.description)}</h2></div><button class="close" data-close-finance>×</button></div><form id="financeEditForm" class="finance-edit-form"><div class="field full"><label>Descrição</label><input name="description" value="${esc(item.description)}" required></div><div class="field"><label>Tipo</label><select name="type"><option value="income" ${item.type==='income'?'selected':''}>Receita</option><option value="expense" ${item.type==='expense'?'selected':''}>Despesa</option></select></div><div class="field"><label>Valor</label><input name="amount" type="number" min="0.01" step="0.01" value="${(item.amount_cents/100).toFixed(2)}" required></div><div class="field"><label>Vencimento</label><input name="due_date" type="date" value="${item.due_date||''}" required></div><div class="field"><label>Status</label><select name="status"><option value="pending" ${item.status==='pending'?'selected':''}>Pendente</option><option value="paid" ${item.status==='paid'?'selected':''}>Pago</option><option value="overdue" ${item.status==='overdue'?'selected':''}>Em atraso</option><option value="void" ${item.status==='void'?'selected':''}>Estornado</option></select></div><div class="finance-detail-actions"><button type="button" class="danger-btn" data-void-finance ${item.status==='void'?'disabled':''}>Estornar</button>${item.status!=='paid'&&item.status!=='void'?'<button type="button" class="secondary-btn" data-pay-finance>Marcar como pago</button>':''}<button class="primary-btn">Salvar alterações</button></div></form>`;dialog.showModal();dialog.querySelector('[data-close-finance]').addEventListener('click',()=>dialog.close());dialog.querySelector('#financeEditForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api.updateFinancialEntry(item.id,{...data,amount:Number(data.amount)});dialog.close();showToast('Lançamento atualizado');await load();window.dispatchEvent(new Event('psyche:refresh'));}catch(err){showToast(err.message);}});dialog.querySelector('[data-pay-finance]')?.addEventListener('click',async()=>{try{await api.updateFinancialEntry(item.id,{status:'paid'});dialog.close();showToast('Pagamento confirmado');await load();}catch(err){showToast(err.message);}});dialog.querySelector('[data-void-finance]').addEventListener('click',async()=>{if(!confirm('Estornar este lançamento? Ele permanecerá no histórico para auditoria.'))return;try{await api.voidFinancialEntry(item.id);dialog.close();showToast('Lançamento estornado');await load();}catch(err){showToast(err.message);}});};
  rows.addEventListener('click',e=>{const row=e.target.closest('[data-finance-id]');if(row)open(items.find(x=>x.id===row.dataset.financeId));});rows.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){const row=e.target.closest('[data-finance-id]');if(row){e.preventDefault();open(items.find(x=>x.id===row.dataset.financeId));}}});
  month.addEventListener('change',load);['financeType','financeStatus'].forEach(id=>document.querySelector(`#${id}`).addEventListener('change',load));document.querySelector('#financeSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(load,300);});
  document.querySelector('#exportFinance').addEventListener('click',()=>{const quote=value=>`"${String(value??'').replaceAll('"','""')}"`,csv=['Vencimento,Descrição,Paciente,Tipo,Valor,Status',...items.map(x=>[x.due_date||'',quote(x.description),quote(x.patient_name||''),x.type,(x.amount_cents/100).toFixed(2),x.status].join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));a.download=`psyche-financeiro-${month.value}.csv`;a.click();showToast('Relatório financeiro exportado');});
  window.addEventListener('psyche:hydrated',load);window.addEventListener('psyche:refresh',load);
  return{load};
}
