import './styles.css';

document.body.classList.add('sales-public');
const privacy=location.pathname.startsWith('/privacidade'),title=privacy?'Política de Privacidade':'Termos de Uso';
const sections=privacy?[
  ['1. Objetivo','Esta política descreve como o Psyché trata dados pessoais na plataforma de gestão destinada a profissionais e organizações de psicologia. A clínica ou profissional contratante atua como controlador dos dados de pacientes e colaboradores inseridos no sistema; o Psyché atua, em regra, como operador conforme as instruções legítimas do controlador.'],
  ['2. Dados tratados','Podemos tratar dados cadastrais, profissionais, contratuais, registros de acesso, informações de cobrança e dados técnicos necessários à segurança. Dados clínicos e informações sensíveis são tratados somente para prestar o serviço contratado, com controles de acesso, segregação por organização e rastreabilidade.'],
  ['3. Finalidades e bases legais','Os dados são utilizados para criar e administrar contas, executar o contrato, proteger a plataforma, prestar suporte, cumprir obrigações legais e comunicar eventos operacionais. Cada clínica é responsável por definir e documentar as bases legais aplicáveis ao cuidado psicológico.'],
  ['4. Compartilhamento e operadores','Dados podem ser processados por fornecedores essenciais de infraestrutura, banco de dados, envio de e-mail, observabilidade e pagamentos, sob obrigações de segurança e confidencialidade. Não comercializamos dados pessoais ou clínicos.'],
  ['5. Segurança e retenção','Aplicamos isolamento por organização, autenticação, criptografia de campos sensíveis, auditoria e controles de permissão. A retenção observará obrigações legais, contratuais e profissionais, evitando exclusão automática de documentação clínica.'],
  ['6. Direitos dos titulares','Solicitações de acesso, correção, portabilidade, informação ou eliminação devem ser encaminhadas primeiramente à clínica responsável pelo atendimento. O Psyché apoiará o controlador no cumprimento dos direitos aplicáveis.'],
  ['7. Contato e alterações','Esta versão entra em vigor em agosto de 2026. Alterações materiais serão comunicadas e poderão exigir novo aceite. O canal oficial de privacidade será informado antes do lançamento comercial.']
]:[
  ['1. Objeto','Estes termos regulam o uso do Psyché, plataforma de apoio à gestão clínica, administrativa, financeira e operacional de profissionais e organizações de psicologia. O sistema não substitui julgamento técnico, supervisão, obrigações éticas ou atendimento emergencial.'],
  ['2. Conta e responsabilidades','O contratante deve fornecer informações verdadeiras, proteger suas credenciais, configurar permissões adequadas e manter somente pessoas autorizadas. Cada usuário responde pelos atos praticados com sua conta, ressalvadas falhas comprovadamente atribuíveis à plataforma.'],
  ['3. Uso profissional e ético','O Psyché deve ser utilizado de acordo com a legislação, a LGPD, normas profissionais e documentos do Conselho Federal de Psicologia aplicáveis. É proibido inserir conteúdo ilícito, usar testes privativos sem autorização ou empregar automações como substitutas da decisão profissional.'],
  ['4. Planos e assinatura','Recursos, limites e preços dependem do plano contratado. Alterações, cancelamento, período de avaliação e renovação seguirão a oferta aceita e as condições apresentadas no momento da contratação. A integração de pagamentos será formalizada antes da cobrança comercial.'],
  ['5. Disponibilidade e integrações','Buscamos manter o serviço disponível e seguro, mas manutenções, falhas de terceiros ou eventos fora do controle razoável podem causar indisponibilidade. Integrações como NFS-e dependem de provedores e municípios compatíveis.'],
  ['6. Dados, exportação e encerramento','Os dados pertencem aos respectivos titulares e controladores. O encerramento da assinatura não autoriza eliminação automática de registros que devam ser preservados. Serão oferecidos meios proporcionais de exportação conforme o plano e as obrigações aplicáveis.'],
  ['7. Propriedade intelectual e alterações','A marca, o software e os elementos visuais do Psyché são protegidos. Esta versão entra em vigor em agosto de 2026 e poderá ser atualizada; mudanças materiais serão informadas e poderão exigir novo aceite.']
];

document.querySelector('#app').innerHTML=`<main class="legal-page"><header><a class="sales-brand" href="/planos"><span>P</span><strong>Psyché</strong></a><a href="/cadastro">Criar conta</a></header><article><span class="sales-kicker">VERSÃO 2026-08 · BASE PARA REVISÃO JURÍDICA</span><h1>${title}</h1><p class="legal-intro">Documento operacional preliminar do Psyché. Antes do lançamento comercial, o conteúdo deverá ser revisado por assessoria jurídica especializada em SaaS, LGPD e saúde.</p>${sections.map(([heading,copy])=>`<section><h2>${heading}</h2><p>${copy}</p></section>`).join('')}<div class="legal-warning"><strong>Aviso de revisão</strong>Este texto organiza as regras técnicas e comerciais já implementadas, mas não constitui parecer jurídico.</div></article></main>`;
