const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusLabel={draft:'Rascunho',active:'Ativa',paused:'Pausada',completed:'Concluída',archived:'Arquivada'};

export function initMarketing({api,showToast}){
  let campaigns=[],feedback=[],patients=[];
  const rows=document.querySelector('#campaignRows');
  document.body.insertAdjacentHTML('beforeend',`<dialog class="crud-dialog campaign-dialog" id="campaignDialog"><div class="modal-head"><div><div class="eyebrow">MARKETING RESPONSÁVEL</div><h2 id="campaignDialogTitle">Nova campanha</h2></div><button class="close" data-close-campaign>×</button></div><form id="campaignForm" class="campaign-form"><div class="field full"><label>Nome da campanha</label><input name="name" required maxlength="160"></div><div class="field"><label>Canal</label><select name="channel"><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option><option value="portal">Portal do paciente</option><option value="email + portal">E-mail + Portal</option></select></div><div class="field"><label>Público</label><select name="audience"><option>Pacientes atendidos</option><option>Novos pacientes</option><option>Pacientes inativos</option><option>Pacientes com retorno agendado</option></select></div><div class="field full consent-check"><label><input type="checkbox" name="consent" required> Confirmo que a campanha será destinada somente a pacientes com consentimento válido.</label></div><div class="modal-actions full"><button type="button" class="secondary-btn" data-close-campaign>Cancelar</button><button class="primary-btn">Salvar campanha</button></div></form></dialog><dialog class="crud-dialog feedback-dialog" id="feedbackDialog"><div class="modal-head"><div><div class="eyebrow">EXPERIÊNCIA DO PACIENTE</div><h2>Registrar feedback</h2></div><button class="close" data-close-feedback>×</button></div><form id="feedbackForm" class="feedback-form"><div class="field"><label>Paciente (opcional)</label><select name="patient_id"><option value="">Feedback anônimo</option></select></div><fieldset><legend>Nota da experiência</legend><div class="score-picker">${[1,2,3,4,5].map(x=>`<label><input type="radio" name="score" value="${x}" required><span>${x} ★</span></label>`).join('')}</div></fieldset><div class="field"><label>Comentário (opcional)</label><textarea name="comment" maxlength="2000" rows="4"></textarea></div><p class="utility-copy">O comentário é armazenado com criptografia. Evite incluir informações clínicas nesta pesquisa.</p><div class="modal-actions"><button type="button" class="secondary-btn" data-close-feedback>Cancelar</button><button class="primary-btn">Registrar avaliação</button></div></form></dialog>`);
  const campaignDialog=document.querySelector('#campaignDialog'),feedbackDialog=document.querySelector('#feedbackDialog');
  const renderCampaigns=()=>{const status=document.querySelector('#campaignStatus').value,visible=status?campaigns.filter(x=>x.status===status):campaigns;document.querySelector('#campaignResultCount').textContent=`${visible.length} ${visible.length===1?'campanha':'campanhas'}`;rows.innerHTML=visible.length?visible.map(x=>`<tr class="campaign-row" data-campaign-id="${x.id}"><td><strong>${esc(x.name)}</strong><small>${new Date(x.created_at).toLocaleDateString('pt-BR')}</small></td><td>${esc(x.channel)}</td><td>${esc(x.audience)}</td><td><span class="campaign-status status-${x.status}">${statusLabel[x.status]||esc(x.status)}</span></td><td><button class="row-action" aria-label="Gerenciar campanha">›</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="agenda-empty marketing-empty"><span>◇</span><strong>Nenhuma campanha encontrada</strong><small>Crie uma automação para fortalecer o relacionamento com consentimento.</small></div></td></tr>';};
  const renderSummary=data=>{const count=Number(data?.count)||0,nps=Number(data?.nps)||0,distribution=data?.distribution||{};document.querySelector('#marketingNps').textContent=String(nps);document.querySelector('#marketingNpsLabel').textContent=count?(nps>=75?'Zona de excelência':nps>=50?'Muito bom':nps>=0?'Aperfeiçoamento':'Atenção necessária'):'Sem avaliações';document.querySelector('#marketingAverage').textContent=count?String(data.average).replace('.',','):'—';document.querySelector('#marketingFeedbackCount').textContent=`${count} ${count===1?'resposta':'respostas'}`;document.querySelector('#marketingPositive').textContent=`${Number(data?.positive_rate)||0}%`;document.querySelector('#marketingActive').textContent=String(Number(data?.active_campaigns)||0);document.querySelector('#marketingDistribution').innerHTML=[5,4,3,2,1].map(score=>{const total=distribution[score]||0,percent=count?Math.round(total/count*100):0;return `<div><span>${score} ★</span><div class="bar"><i style="width:${percent}%"></i></div><b>${total}</b></div>`;}).join('');};
  const renderFeedback=()=>{document.querySelector('#marketingFeedbackList').innerHTML=feedback.length?feedback.slice(0,8).map(x=>`<article class="feedback-item"><div><strong>${'★'.repeat(x.score)}${'☆'.repeat(5-x.score)}</strong><time>${new Date(x.created_at).toLocaleDateString('pt-BR')}</time></div><p>${esc(x.comment||'Avaliação sem comentário.')}</p><small>${esc(x.patient_name||'Paciente anônimo')}</small></article>`).join(''):'<div class="feedback-list-empty"><span>☆</span><strong>Nenhuma avaliação ainda</strong><small>Os feedbacks registrados aparecerão aqui.</small></div>';};
  const load=async()=>{if(!api.token)return;rows.innerHTML='<tr><td colspan="5"><div class="dashboard-loading">Carregando campanhas...</div></td></tr>';try{const [campaignResult,feedbackResult,summaryResult]=await Promise.all([api.campaigns(),api.feedback(),api.feedbackSummary()]);campaigns=campaignResult.data;feedback=feedbackResult.data;renderCampaigns();renderFeedback();renderSummary(summaryResult.data);}catch(err){rows.innerHTML=`<tr><td colspan="5"><div class="dashboard-error">${esc(err.message)}</div></td></tr>`;}};
  const openCampaign=item=>{const form=document.querySelector('#campaignForm');form.reset();form.dataset.id=item?.id||'';document.querySelector('#campaignDialogTitle').textContent=item?'Gerenciar campanha':'Nova campanha';if(item){form.elements.name.value=item.name;form.elements.channel.value=item.channel;form.elements.audience.value=item.audience;form.elements.consent.checked=true;}campaignDialog.showModal();};
  document.querySelector('.marketing-action').addEventListener('click',()=>openCampaign());document.querySelectorAll('[data-close-campaign]').forEach(x=>x.addEventListener('click',()=>campaignDialog.close()));document.querySelector('#campaignForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{if(e.target.dataset.id)await api.updateCampaign(e.target.dataset.id,{name:data.name,channel:data.channel,audience:data.audience});else await api.createCampaign({name:data.name,channel:data.channel,audience:data.audience});campaignDialog.close();showToast('Campanha salva');await load();}catch(err){showToast(err.message);}});
  rows.addEventListener('click',e=>{const row=e.target.closest('[data-campaign-id]');if(!row)return;const item=campaigns.find(x=>x.id===row.dataset.campaignId),utility=document.querySelector('#utilityDialog');document.querySelector('#utilityTitle').textContent=item.name;document.querySelector('#utilityContent').innerHTML=`<div class="campaign-detail"><p><span>Canal</span><strong>${esc(item.channel)}</strong></p><p><span>Público</span><strong>${esc(item.audience)}</strong></p></div><div class="campaign-actions">${item.status!=='active'?'<button class="primary-btn" data-campaign-status="active">Ativar campanha</button>':'<button class="secondary-btn" data-campaign-status="paused">Pausar campanha</button>'}<button class="secondary-btn" data-edit-campaign>Editar</button><button class="danger-btn" data-archive-campaign>Arquivar</button></div><p class="utility-copy">A ativação registra a campanha. O disparo por provedores externos será executado somente após configurar a integração correspondente.</p>`;utility.showModal();utility.querySelector('[data-campaign-status]').addEventListener('click',async ev=>{try{await api.updateCampaign(item.id,{status:ev.currentTarget.dataset.campaignStatus});utility.close();showToast('Status da campanha atualizado');await load();}catch(err){showToast(err.message);}});utility.querySelector('[data-edit-campaign]').addEventListener('click',()=>{utility.close();openCampaign(item);});utility.querySelector('[data-archive-campaign]').addEventListener('click',async()=>{if(!confirm('Arquivar esta campanha?'))return;try{await api.archiveCampaign(item.id);utility.close();showToast('Campanha arquivada');await load();}catch(err){showToast(err.message);}});});
  document.querySelector('#campaignStatus').addEventListener('change',renderCampaigns);
  document.querySelector('#newFeedback').addEventListener('click',()=>{const select=document.querySelector('#feedbackForm [name="patient_id"]');select.innerHTML='<option value="">Feedback anônimo</option>'+patients.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');feedbackDialog.showModal();});document.querySelectorAll('[data-close-feedback]').forEach(x=>x.addEventListener('click',()=>feedbackDialog.close()));document.querySelector('#feedbackForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));try{await api.createFeedback({patient_id:data.patient_id||null,score:Number(data.score),comment:data.comment});feedbackDialog.close();form.reset();showToast('Feedback registrado com segurança');await load();window.dispatchEvent(new Event('psyche:refresh'));}catch(err){showToast(err.message);}});
  window.addEventListener('psyche:hydrated',e=>{patients=e.detail.patients||[];load();});window.addEventListener('psyche:refresh',load);
  return{load};
}
