const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusLabel={pending:'Aguardando',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado',no_show:'Não compareceu'};

export function initReports({api,showToast}){
  let report=null,loading=false;
  const from=document.querySelector('#reportFrom'),to=document.querySelector('#reportTo'),professionals=document.querySelector('#reportProfessionalRows');
  const today=new Date(),first=new Date(today.getFullYear(),today.getMonth(),1),iso=date=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`;};from.value=iso(first);to.value=iso(today);
  const renderChart=data=>{const chart=document.querySelector('#reportChart');if(!data.length){chart.innerHTML='<div class="report-empty"><span>⌁</span><strong>Sem movimentação neste período</strong><small>Altere o intervalo para visualizar a evolução.</small></div>';return;}const maximum=Math.max(...data.map(x=>x.total),1);chart.innerHTML=`<div class="report-chart-bars">${data.map(x=>`<div class="report-chart-column" title="${x.total} agendados · ${x.completed} concluídos"><div><i style="height:${Math.max(x.completed/maximum*100,3)}%"></i><b style="height:${Math.max((x.total-x.completed)/maximum*100,0)}%"></b></div><span>${new Date(`${x.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span><strong>${x.total}</strong></div>`).join('')}</div><div class="report-chart-legend"><span><i></i>Concluídos</span><span><i></i>Outros status</span></div>`;};
  const render=data=>{report=data;const m=data.metrics;document.querySelector('#reportAppointments').textContent=String(m.appointments);document.querySelector('#reportCompletion').textContent=`Conclusão: ${m.completion_rate}%`;document.querySelector('#reportOccupancy').textContent=`${m.occupancy_rate}%`;document.querySelector('#reportRetention').textContent=`${m.retention_rate}%`;document.querySelector('#reportTicket').textContent=money(m.average_ticket_cents);const net=document.querySelector('#reportNet');net.textContent=money(m.net_cents);net.classList.toggle('negative',m.net_cents<0);document.querySelector('#reportFinanceCopy').textContent=`${money(m.income_cents)} em receitas · ${money(m.expense_cents)} em despesas`;document.querySelector('#reportActivePatients').textContent=String(m.active_patients);document.querySelector('#reportNewPatients').textContent=String(m.new_patients);document.querySelector('#reportPeriodLabel').textContent=`${new Date(`${data.period.from}T12:00:00`).toLocaleDateString('pt-BR')} a ${new Date(`${data.period.to}T12:00:00`).toLocaleDateString('pt-BR')} · ${data.period.days} dias`;renderChart(data.daily_appointments);const total=Math.max(m.appointments,1);document.querySelector('#reportStatuses').innerHTML=Object.entries(statusLabel).map(([key,label])=>{const value=data.statuses[key]||0,percent=Math.round(value/total*100);return `<div class="report-status-row"><div><span>${label}</span><b>${value}</b></div><div class="bar"><i class="status-${key}" style="width:${percent}%"></i></div><small>${percent}%</small></div>`;}).join('');professionals.innerHTML=data.professionals.length?data.professionals.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${x.appointments}</td><td>${x.completed}</td><td>${x.losses}</td><td><span class="report-conversion">${x.appointments?Math.round(x.completed/x.appointments*100):0}%</span></td></tr>`).join(''):'<tr><td colspan="5"><div class="agenda-empty report-table-empty"><span>♧</span><strong>Sem produção profissional</strong><small>Nenhum atendimento encontrado no período.</small></div></td></tr>';};
  const load=async()=>{if(!api.token||loading)return;if(!from.value||!to.value||from.value>to.value){showToast('Informe um período válido');return;}loading=true;professionals.innerHTML='<tr><td colspan="5"><div class="dashboard-loading">Calculando indicadores...</div></td></tr>';try{const result=await api.reports({from:from.value,to:to.value});render(result.data);}catch(err){professionals.innerHTML=`<tr><td colspan="5"><div class="dashboard-error">${esc(err.message)}</div></td></tr>`;showToast(err.message);}finally{loading=false;}};
  const exportCsv=()=>{if(!report){showToast('Aguarde o carregamento do relatório');return;}const m=report.metrics,lines=[['Relatório Psyché',`${report.period.from} a ${report.period.to}`],[],['Indicador','Valor'],['Atendimentos',m.appointments],['Concluídos',m.completed],['Taxa de conclusão',`${m.completion_rate}%`],['Ocupação',`${m.occupancy_rate}%`],['Retenção',`${m.retention_rate}%`],['Receitas',(m.income_cents/100).toFixed(2)],['Despesas',(m.expense_cents/100).toFixed(2)],['Resultado líquido',(m.net_cents/100).toFixed(2)],['Ticket médio',(m.average_ticket_cents/100).toFixed(2)],[],['Profissional','Agendados','Concluídos','Perdas'],...report.professionals.map(x=>[x.name,x.appointments,x.completed,x.losses])],quote=value=>`"${String(value??'').replaceAll('"','""')}"`,csv=lines.map(line=>line.map(quote).join(',')).join('\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));link.download=`psyche-relatorio-${report.period.from}-${report.period.to}.csv`;link.click();showToast('Relatório gerencial exportado');};
  document.querySelector('#reportApply').addEventListener('click',load);document.querySelector('.reports-action').addEventListener('click',exportCsv);window.addEventListener('psyche:hydrated',load);window.addEventListener('psyche:refresh',load);
  return{load,exportCsv};
}
