const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];

export function initSchedules({api,showToast}){
  let units=[],current=null;
  document.body.insertAdjacentHTML('beforeend',`<dialog class="crud-dialog schedule-dialog" id="scheduleDialog"><div class="modal-head"><div><div class="eyebrow">AGENDA DISPONÍVEL</div><h2 id="scheduleTitle">Horários semanais</h2></div><button class="close" data-close-schedule>×</button></div><p class="utility-copy" id="scheduleDescription"></p><form id="scheduleForm"><div class="schedule-week" id="scheduleWeek"></div><div class="modal-actions"><button type="button" class="secondary-btn" data-close-schedule>Cancelar</button><button class="primary-btn">Salvar horários</button></div></form></dialog>`);
  const dialog=document.querySelector('#scheduleDialog'),week=document.querySelector('#scheduleWeek');
  const row=(weekday,rules,scope)=>{const rule=rules.find(item=>Number(item.weekday)===weekday)||{},unitOptions=units.map(unit=>`<option value="${unit.id}" ${rule.unit_id===unit.id?'selected':''}>${esc(unit.name)}</option>`).join('');return `<fieldset class="schedule-day"><label class="schedule-day-toggle"><input type="checkbox" name="day_${weekday}" ${rule.id?'checked':''}><strong>${days[weekday]}</strong></label><div class="schedule-day-fields">${scope==='professionals'?`<label>Unidade<select name="unit_${weekday}">${unitOptions}</select></label>`:''}<label>Consultório<input name="room_${weekday}" value="${esc(rule.room||'')}" placeholder="Todos"></label><label>Início<input name="opens_${weekday}" type="time" value="${rule.opens_time||'08:00'}"></label><label>Término<input name="closes_${weekday}" type="time" value="${rule.closes_time||'18:00'}"></label>${scope==='professionals'?`<label>Duração padrão<input name="slot_${weekday}" type="number" min="20" max="240" value="${rule.slot_minutes||50}"></label>`:''}</div></fieldset>`;};
  const open=async(scope,id,name)=>{current={scope,id};document.querySelector('#scheduleTitle').textContent=scope==='professionals'?`Disponibilidade de ${name}`:`Funcionamento de ${name}`;document.querySelector('#scheduleDescription').textContent=scope==='professionals'?'O agendamento será permitido somente quando coincidir com estes horários e com o funcionamento da unidade/consultório.':'Defina os horários em que cada unidade e consultório aceita agendamentos.';try{const result=await api.scheduleRules(scope,id);week.innerHTML=days.map((_,day)=>row(day,result.data,scope)).join('');dialog.showModal();}catch(error){showToast(error.message);}};
  document.querySelectorAll('[data-close-schedule]').forEach(button=>button.addEventListener('click',()=>dialog.close()));document.querySelector('#scheduleForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),rules=[];for(let weekday=0;weekday<7;weekday++){if(!data.get(`day_${weekday}`))continue;rules.push({weekday,unit_id:current.scope==='professionals'?data.get(`unit_${weekday}`):current.id,room:data.get(`room_${weekday}`),opens_time:data.get(`opens_${weekday}`),closes_time:data.get(`closes_${weekday}`),slot_minutes:Number(data.get(`slot_${weekday}`)||50)});}try{await api.updateScheduleRules(current.scope,current.id,rules);dialog.close();showToast(rules.length?'Horários de agenda atualizados':'Agenda fechada: nenhum horário disponível');}catch(error){showToast(error.message);}});
  document.addEventListener('click',event=>{const team=event.target.closest('[data-team-schedule]');if(team){event.preventDefault();event.stopImmediatePropagation();return open('professionals',team.dataset.teamSchedule,team.dataset.name);}const unit=event.target.closest('[data-unit-schedule]');if(unit){event.preventDefault();event.stopImmediatePropagation();return open('units',unit.dataset.unitSchedule,unit.dataset.name);}},true);
  const enhance=()=>{const teamActions=document.querySelector('#teamProfile .modal-actions');const teamId=document.querySelector('#teamProfileContent h2')?.textContent;if(teamActions&&!teamActions.querySelector('[data-team-schedule]')){const member=document.querySelector(`[data-team-id] strong`);const found=window.__psycheTeamItems?.find(item=>item.name===teamId);if(found&&['admin','professional'].includes(found.role))teamActions.insertAdjacentHTML('afterbegin',`<button type="button" class="secondary-btn" data-team-schedule="${found.id}" data-name="${esc(found.name)}">Horários disponíveis</button>`);}document.querySelectorAll('#settingsUnitList [data-unit-id]').forEach(button=>{if(button.querySelector('[data-unit-schedule]'))return;const unit=units.find(item=>item.id===button.dataset.unitId);if(unit)button.insertAdjacentHTML('beforeend',`<span role="button" class="schedule-unit-button" data-unit-schedule="${unit.id}" data-name="${esc(unit.name)}">Horários</span>`);});};new MutationObserver(enhance).observe(document.body,{subtree:true,childList:true});
  window.addEventListener('psyche:hydrated',event=>{units=event.detail.units||[];window.__psycheTeamItems=event.detail.team||[];enhance();});
  window.addEventListener('psyche:refresh',()=>setTimeout(()=>{const created=window.__psycheNewTeamMember?.data;if(created&&['admin','professional'].includes(created.role)){window.__psycheNewTeamMember=null;open('professionals',created.id,created.name);}},250));
  return{open};
}
