const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=name=>String(name||'').split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const integrationOptions={patient_portal:['Portal do paciente','Pagamentos, materiais e mensagens em um ambiente protegido'],automatic_confirmation:['Confirmação automática','Lembretes de atendimento pelo canal configurado'],video_consultation:['Videoconsulta','Links seguros vinculados aos agendamentos'],payments:['Pagamentos online','Conciliação com o portal do paciente']};
const notificationOptions={email_appointments:['Agenda por e-mail','Alterações, confirmações e cancelamentos'],email_finance:['Alertas financeiros','Vencimentos e valores em atraso'],browser_messages:['Mensagens no navegador','Avisos de novas mensagens de pacientes'],daily_summary:['Resumo diário','Indicadores operacionais no início do dia']};

export function initSettings({api,showToast}){
  let units=[],services=[],config={},tenant=window.__psycheTenantContext;
  document.querySelector('.settings-nav').insertAdjacentHTML('beforeend','<button data-settings-tab="modules">Plano e módulos</button>');
  document.querySelector('.settings-panels').insertAdjacentHTML('beforeend','<section class="card panel settings-panel" data-settings-panel="modules"><div class="panel-head"><div><div class="panel-title">Plano e módulos</div><div class="panel-sub">Funcionalidades habilitadas para esta clínica</div></div><span class="tag" id="tenantPlanBadge">Plano</span></div><div class="tenant-usage" id="tenantUsage"></div><div class="settings-toggle-list" id="tenantModules"></div><p class="utility-copy">A desativação é aplicada imediatamente no menu e na API. Módulos fora do plano exigem alteração da assinatura.</p></section>');
  document.querySelector('.settings-nav').insertAdjacentHTML('beforeend','<button data-settings-tab="billing">Cobrança e ética</button>');
  document.querySelector('.settings-panels').insertAdjacentHTML('beforeend',`<section class="card panel settings-panel" data-settings-panel="billing"><div class="panel-head"><div><div class="panel-title">Política de cobrança</div><div class="panel-sub">Regras administrativas acordadas sem automatizar decisões clínicas</div></div></div><form id="billingPolicyForm" class="billing-policy-form"><div class="field"><label>Momento previsto da cobrança</label><select name="timing"><option value="after_session">Após o atendimento</option><option value="before_session">Antes do atendimento</option><option value="before_booking">Antes de confirmar o agendamento</option></select></div><div class="field"><label>Tolerância após vencimento</label><input name="grace_days" type="number" min="0" max="90"><small>Quantidade de dias antes do alerta de pendência.</small></div><div class="field"><label>Conduta em caso de atraso</label><select name="overdue_action"><option value="warn">Apenas alertar</option><option value="review">Solicitar revisão administrativa</option></select></div><div class="field"><label>Prazo para cancelamento sem cobrança</label><input name="cancellation_hours" type="number" min="0" max="168"><small>Deve constar no contrato e ser informado previamente.</small></div><div class="field"><label>Percentual acordado para falta</label><input name="no_show_charge_percent" type="number" min="0" max="100"><small>Aplicável somente quando previsto e aceito no contrato.</small></div><label class="billing-check"><input name="allow_clinical_override" type="checkbox"> Permitir decisão profissional justificada diante de vulnerabilidade</label><label class="billing-check"><input name="emergency_never_block" type="checkbox" checked disabled> Nunca bloquear cuidado urgente ou emergencial automaticamente</label><div class="clinical-ethics-note"><strong>Regra do Psyché</strong><br>O sistema informa pendências e apoia revisão administrativa. Não interrompe atendimento automaticamente, não reduz a qualidade do serviço e não substitui o acordo de honorários nem a avaliação ética da situação concreta.</div><div class="modal-actions"><button class="primary-btn">Salvar política</button></div></form></section>`);
  document.body.insertAdjacentHTML('beforeend',`<dialog class="crud-dialog setting-editor" id="settingEditor"><div class="modal-head"><div><div class="eyebrow">CONFIGURAÇÕES</div><h2 id="settingEditorTitle"></h2></div><button class="close" data-close-setting>×</button></div><form id="settingEditorForm" class="setting-editor-form"><div id="settingEditorFields"></div><div class="modal-actions"><button type="button" class="secondary-btn" data-close-setting>Cancelar</button><button class="primary-btn">Salvar</button></div></form></dialog>`);
  const editor=document.querySelector('#settingEditor'),form=document.querySelector('#settingEditorForm');
  const renderUnits=()=>{document.querySelector('#settingsUnitList').innerHTML=units.length?units.map((u,i)=>`<button class="settings-entity ${u.active?'':'inactive'}" data-unit-id="${u.id}"><span class="clinic-dot">${initials(u.name)}</span><span><strong>${esc(u.name)}</strong><small>${u.rooms} ${u.rooms===1?'consultório':'consultórios'} · ${esc(u.address||'Endereço não informado')}</small></span><span class="tag ${u.active?'':'gray'}">${i===0&&u.active?'Principal':u.active?'Ativa':'Inativa'}</span><b>›</b></button>`).join(''):'<div class="settings-empty">Nenhuma unidade cadastrada.</div>';};
  const renderServices=()=>{document.querySelector('#settingsServiceList').innerHTML=services.length?services.map(s=>`<button class="settings-entity ${s.active?'':'inactive'}" data-service-id="${s.id}"><span class="service-icon">◷</span><span><strong>${esc(s.name)}</strong><small>${s.duration_minutes} minutos · ${money(s.price_cents)}</small></span><span class="tag ${s.active?'':'gray'}">${s.active?'Ativo':'Inativo'}</span><b>›</b></button>`).join(''):'<div class="settings-empty"><strong>Nenhum serviço cadastrado</strong><span>Adicione os serviços oferecidos pela clínica.</span></div>';};
  const toggleList=(target,section,options)=>{const values=config[section]||{};document.querySelector(target).innerHTML=Object.entries(options).map(([key,[title,copy]])=>`<div class="settings-toggle-row"><div><strong>${title}</strong><span>${copy}</span></div><button class="toggle ${values[key]?'active':''}" role="switch" aria-checked="${Boolean(values[key])}" data-setting-section="${section}" data-setting-key="${key}" aria-label="${title}"></button></div>`).join('');};
  const renderConfig=()=>{toggleList('#settingsIntegrations','integrations',integrationOptions);toggleList('#settingsNotifications','notifications',notificationOptions);const security=config.security||{};document.querySelector('#settingsSecurity').innerHTML=`<label class="settings-select-row"><span><strong>Validade máxima da sessão</strong><small>Exige novo login ao término deste período</small></span><select id="sessionTimeout"><option value="60">1 hora</option><option value="240">4 horas</option><option value="480">8 horas</option><option value="720">12 horas</option></select></label><div class="settings-toggle-row setting-unavailable"><div><strong>Autenticação em dois fatores</strong><span>Será habilitada com o provedor de identidade da infraestrutura de produção</span></div><span class="tag gray">Pendente</span></div><div class="settings-toggle-list">${[['clinical_audit','Auditoria de acessos clínicos','Registra leitura e alteração de dados sensíveis'],['data_export_enabled','Permitir exportação de dados','Disponibiliza relatórios conforme a política da clínica']].map(([key,title,copy])=>`<div class="settings-toggle-row"><div><strong>${title}</strong><span>${copy}</span></div><button class="toggle ${security[key]?'active':''}" role="switch" aria-checked="${Boolean(security[key])}" data-setting-section="security" data-setting-key="${key}"></button></div>`).join('')}</div>`;document.querySelector('#sessionTimeout').value=String(security.session_timeout_minutes||480);};
  const renderBilling=()=>{const form=document.querySelector('#billingPolicyForm'),billing=config.billing||{};form.elements.timing.value=billing.timing||'after_session';form.elements.grace_days.value=billing.grace_days??3;form.elements.overdue_action.value=billing.overdue_action||'warn';form.elements.cancellation_hours.value=billing.cancellation_hours??24;form.elements.no_show_charge_percent.value=billing.no_show_charge_percent??100;form.elements.allow_clinical_override.checked=billing.allow_clinical_override!==false;};
  const renderTenant=()=>{if(!tenant)return;document.querySelector('#tenantPlanBadge').textContent=`${tenant.subscription.plan_name} · ${tenant.subscription.status==='active'?'Ativo':tenant.subscription.status}`;const labels={users:'Usuários',units:'Unidades',patients:'Pacientes'};document.querySelector('#tenantUsage').innerHTML=Object.entries(labels).map(([key,label])=>`<div><span>${label}</span><strong>${tenant.usage[key]} <small>/ ${tenant.limits[key]??'ilimitado'}</small></strong></div>`).join('');document.querySelector('#tenantModules').innerHTML=Object.entries(tenant.modules).map(([key,module])=>`<div class="settings-toggle-row"><div><strong>${esc(module.name)}</strong><span>${esc(module.description)}</span></div><button class="toggle ${module.enabled?'active':''}" role="switch" aria-checked="${Boolean(module.enabled)}" data-tenant-module="${key}" ${key==='core'?'disabled title="Módulo obrigatório"':''}></button></div>`).join('');};
  const load=async()=>{if(!api.token)return;try{const [unitResult,serviceResult,settingResult]=await Promise.all([api.units(),api.services(),api.settings()]);units=unitResult.data;services=serviceResult.data;config=settingResult.data;renderUnits();renderServices();renderConfig();renderBilling();}catch(err){showToast(err.message);}};
  const openUnit=item=>{form.dataset.type='unit';form.dataset.id=item?.id||'';document.querySelector('#settingEditorTitle').textContent=item?'Editar unidade':'Adicionar unidade';document.querySelector('#settingEditorFields').innerHTML=`<div class="form-grid"><div class="field full"><label>Nome</label><input name="name" value="${esc(item?.name||'')}" required></div><div class="field full"><label>Endereço</label><input name="address" value="${esc(item?.address||'')}"></div><div class="field"><label>Consultórios</label><input name="rooms" type="number" min="1" max="100" value="${item?.rooms||1}" required></div>${item?`<div class="field"><label>Status</label><select name="active"><option value="true" ${item.active?'selected':''}>Ativa</option><option value="false" ${!item.active?'selected':''}>Inativa</option></select></div>`:''}</div>`;editor.showModal();};
  const openService=item=>{form.dataset.type='service';form.dataset.id=item?.id||'';document.querySelector('#settingEditorTitle').textContent=item?'Editar serviço':'Adicionar serviço';document.querySelector('#settingEditorFields').innerHTML=`<div class="form-grid"><div class="field full"><label>Nome do serviço</label><input name="name" value="${esc(item?.name||'')}" required></div><div class="field"><label>Duração</label><input name="duration_minutes" type="number" min="15" max="300" value="${item?.duration_minutes||50}" required></div><div class="field"><label>Valor</label><input name="price" type="number" min="0" step="0.01" value="${item?(item.price_cents/100).toFixed(2):''}" required></div>${item?`<div class="field"><label>Status</label><select name="active"><option value="true" ${item.active?'selected':''}>Ativo</option><option value="false" ${!item.active?'selected':''}>Inativo</option></select></div>`:''}</div>`;editor.showModal();};
  document.querySelectorAll('[data-settings-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-settings-panel]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===button.dataset.settingsTab));}));
  document.querySelector('.settings-action').addEventListener('click',()=>openUnit());document.querySelector('#settingsAddUnit').addEventListener('click',()=>openUnit());document.querySelector('#settingsAddService').addEventListener('click',()=>openService());document.querySelector('#settingsUnitList').addEventListener('click',e=>{const row=e.target.closest('[data-unit-id]');if(row)openUnit(units.find(x=>x.id===row.dataset.unitId));});document.querySelector('#settingsServiceList').addEventListener('click',e=>{const row=e.target.closest('[data-service-id]');if(row)openService(services.find(x=>x.id===row.dataset.serviceId));});document.querySelectorAll('[data-close-setting]').forEach(x=>x.addEventListener('click',()=>editor.close()));
  form.addEventListener('submit',async e=>{e.preventDefault();const formElement=e.currentTarget,data=Object.fromEntries(new FormData(formElement));try{if(formElement.dataset.type==='unit'){const payload={name:data.name,address:data.address,rooms:Number(data.rooms),...(data.active?{active:data.active==='true'}:{})};if(formElement.dataset.id)await api.updateUnit(formElement.dataset.id,payload);else await api.createUnit(payload);}else{const payload={name:data.name,duration_minutes:Number(data.duration_minutes),price:Number(data.price),...(data.active?{active:data.active==='true'}:{})};if(formElement.dataset.id)await api.updateService(formElement.dataset.id,payload);else await api.createService(payload);}editor.close();showToast('Configuração salva no backend');await load();window.dispatchEvent(new Event('psyche:refresh'));}catch(err){showToast(err.message);}});
  document.querySelector('#billingPolicyForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),billing={timing:data.timing,grace_days:Number(data.grace_days),overdue_action:data.overdue_action,cancellation_hours:Number(data.cancellation_hours),no_show_charge_percent:Number(data.no_show_charge_percent),allow_clinical_override:Boolean(data.allow_clinical_override),emergency_never_block:true};try{await api.updateSettings({billing});config.billing=billing;showToast('Política ética de cobrança atualizada');}catch(err){showToast(err.message);}});
  document.querySelector('.settings-panels').addEventListener('click',async e=>{const toggle=e.target.closest('[data-setting-key]');if(!toggle)return;const section=toggle.dataset.settingSection,key=toggle.dataset.settingKey,next=!Boolean(config[section]?.[key]),updated={...(config[section]||{}),[key]:next};try{await api.updateSettings({[section]:updated});config[section]=updated;renderConfig();showToast('Preferência atualizada');}catch(err){showToast(err.message);}});document.querySelector('#settingsSecurity').addEventListener('change',async e=>{if(e.target.id!=='sessionTimeout')return;const updated={...(config.security||{}),session_timeout_minutes:Number(e.target.value)};try{await api.updateSettings({security:updated});config.security=updated;showToast('Política de sessão atualizada');}catch(err){showToast(err.message);}});
  window.addEventListener('psyche:hydrated',load);window.addEventListener('psyche:refresh',load);
  window.addEventListener('psyche:tenant-context',event=>{tenant=event.detail;renderTenant();});renderTenant();document.querySelector('#tenantModules').addEventListener('click',async event=>{const toggle=event.target.closest('[data-tenant-module]');if(!toggle||toggle.disabled)return;const key=toggle.dataset.tenantModule,next=!tenant.modules[key].enabled;if(!confirm(`${next?'Ativar':'Desativar'} o módulo ${tenant.modules[key].name}?`))return;try{const{data}=await api.configureModule(key,next,'Configuração realizada pela clínica');tenant=data;renderTenant();window.__psycheApplyTenantContext?.(data);showToast(`Módulo ${next?'ativado':'desativado'}`);}catch(error){showToast(error.message);}});
  return{load};
}
