import './styles.css';
import { api } from './api.js';
import { commercialPlans, money } from './plans.js';

document.body.classList.add('sales-public');
const app=document.querySelector('#app'),params=new URLSearchParams(location.search),verifyRoute=location.pathname.includes('/verificar');

if(verifyRoute){
  app.innerHTML=`<main class="signup-page"><a class="sales-brand" href="/planos"><span>P</span><strong>Psyché</strong></a><section class="signup-card signup-verify"><div class="signup-spinner"></div><h1>Validando seu cadastro</h1><p id="verifyMessage">Aguarde enquanto preparamos seu ambiente seguro.</p><a class="sales-primary" href="/" id="verifyLogin" hidden>Entrar no Psyché</a></section></main>`;
  const token=params.get('token');
  if(!token)document.querySelector('#verifyMessage').textContent='O link de verificação está incompleto.';
  else api.verifySignup(token).then(result=>{document.querySelector('.signup-spinner').textContent='✓';document.querySelector('.signup-spinner').classList.add('done');document.querySelector('h1').textContent='Cadastro confirmado';document.querySelector('#verifyMessage').textContent=`${result.message} Seu período de avaliação é de 14 dias.`;document.querySelector('#verifyLogin').hidden=false;}).catch(error=>{document.querySelector('.signup-spinner').textContent='!';document.querySelector('.signup-spinner').classList.add('error');document.querySelector('h1').textContent='Não foi possível validar';document.querySelector('#verifyMessage').textContent=error.message;});
}else{
  const selected=commercialPlans.find(plan=>plan.key===params.get('plano'))||commercialPlans[0],cycle=params.get('ciclo')==='yearly'?'yearly':'monthly';
  app.innerHTML=`<main class="signup-page"><a class="sales-brand" href="/planos"><span>P</span><strong>Psyché</strong></a><div class="signup-layout"><section class="signup-card"><span class="sales-kicker">CRIE SEU AMBIENTE</span><h1>Comece a organizar sua prática.</h1><p>Informe seus dados para criar o período de avaliação. Confirme o e-mail antes de acessar o sistema.</p><form id="signupForm"><div class="form-grid"><div class="field"><label>Seu nome completo</label><input name="professional_name" required maxlength="160" autocomplete="name"></div><div class="field"><label>Nome do consultório ou clínica</label><input name="clinic_name" required maxlength="180" autocomplete="organization"></div><div class="field"><label>E-mail profissional</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>Telefone</label><input name="phone" maxlength="30" autocomplete="tel"></div><div class="field"><label>CPF ou CNPJ <small>(opcional)</small></label><input name="clinic_document" maxlength="30"></div><div class="field"><label>Senha</label><input name="password" type="password" minlength="8" required autocomplete="new-password"><small>Mínimo de 8 caracteres, com letras e números.</small></div><div class="field"><label>Plano</label><select name="plan_key">${commercialPlans.map(plan=>`<option value="${plan.key}" ${plan.key===selected.key?'selected':''}>${plan.name}</option>`).join('')}</select></div><div class="field"><label>Ciclo</label><select name="billing_cycle"><option value="monthly" ${cycle==='monthly'?'selected':''}>Mensal</option><option value="yearly" ${cycle==='yearly'?'selected':''}>Anual — 10% de desconto</option></select></div></div><label class="signup-check"><input name="accept_terms" type="checkbox" required> Li e aceito os <a href="/termos" target="_blank">Termos de Uso</a>.</label><label class="signup-check"><input name="accept_privacy" type="checkbox" required> Li e aceito a <a href="/privacidade" target="_blank">Política de Privacidade</a>.</label><div class="auth-error" id="signupError" role="alert"></div><button class="sales-primary" id="signupSubmit">Criar meu ambiente</button></form><div class="signup-success" id="signupSuccess" hidden></div></section><aside class="signup-summary"><span class="sales-kicker">SUA ESCOLHA</span><h2 id="summaryPlan">${selected.name}</h2><strong id="summaryPrice">${money(cycle==='yearly'?selected.yearlyCents:selected.monthlyCents)}</strong><span id="summaryCycle">${cycle==='yearly'?'por ano':'por mês'}</span><ul id="summaryFeatures">${selected.features.map(item=>`<li>✓ ${item}</li>`).join('')}</ul><p>14 dias para conhecer o Psyché. Nenhuma cobrança será realizada enquanto o Mercado Pago não estiver integrado e a contratação não for confirmada.</p></aside></div></main>`;
  const form=document.querySelector('#signupForm'),renderSummary=()=>{const plan=commercialPlans.find(item=>item.key===form.elements.plan_key.value),annual=form.elements.billing_cycle.value==='yearly';document.querySelector('#summaryPlan').textContent=plan.name;document.querySelector('#summaryPrice').textContent=money(annual?plan.yearlyCents:plan.monthlyCents);document.querySelector('#summaryCycle').textContent=annual?'por ano':'por mês';document.querySelector('#summaryFeatures').innerHTML=plan.features.map(item=>`<li>✓ ${item}</li>`).join('');};
  form.addEventListener('change',event=>{if(['plan_key','billing_cycle'].includes(event.target.name))renderSummary();});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('#signupSubmit'),error=document.querySelector('#signupError'),data=Object.fromEntries(new FormData(form));data.accept_terms=Boolean(data.accept_terms);data.accept_privacy=Boolean(data.accept_privacy);button.disabled=true;button.textContent='Enviando...';error.textContent='';try{const result=await api.signup(data);form.hidden=true;const success=document.querySelector('#signupSuccess');success.hidden=false;success.innerHTML=`<span>✓</span><h2>Confira seu e-mail</h2><p>${result.message}</p>${result.data.verification_url?`<a class="sales-primary" href="${result.data.verification_url}">Verificar cadastro localmente</a><small>Este botão aparece somente no ambiente de desenvolvimento.</small>`:''}`;}catch(err){error.textContent=err.message;}finally{button.disabled=false;button.textContent='Criar meu ambiente';}});
}
